### ISSUE TITLE
Streaming history import not started - MulterError: File too large

### ISSUE THREAD

**Issue by karpaterna** [Yooooomi/your_spotify#101]
**Describe the bug**
After trying to import my files from private data request history, I see an error 500 with error message "MulterError: File too large" present in logs. My files are around 11mb in size. I am running this behind a reverse proxy.

**Expected behavior**
After starting the import with my selected files, it should process and finish.

**Comment by Yooooomi** [comment]
Oh that's weird, I explicity set the multer max file size to 20mb [here](https://github.com/Yooooomi/your_spotify/blob/d17afac879a08b53e1c5c6227112db2e4e40dacb/server/src/routes/importer.ts#L18). Can you send the full log of the error?

**Comment by karpaterna** [comment]
I just updated to the latest version and the issue is gone :) Thx for amazing software, closing the issue.
