### ISSUE TITLE
Feature request - genre statistics

### ISSUE THREAD

**Issue by the-citizenfour** [Yooooomi/your_spotify#104]
Hi

It would be nice if there would be some additional statistics about the genres I've listened to.
Would it be possible to implement something in this direction in the future?

Thanks :)

**Comment by Yooooomi** [comment]
Hello, sorry for the late reply. I already thought about genre statistics, however they are really messy in the Spotify API and do not permit to _quite easily_ get statistics out of them.
This is an example but they can get even more weird:
<img width="132" alt="image" src="https://user-images.githubusercontent.com/17204739/161419296-e949b0e3-c3c2-4bcd-8732-9166ae422745.png">
There is also a limitation where a song can be not classified yet, thus requiring some later request to get them.
Thanks a lot for your feedback. If I ever have an idea on how to do it I'll try but not for now I guess.

**Comment by CaptaiNiveau** [comment]
Hi, I just got YourSpotify up and running. The stats are awesome!
However, I'd love to see Genre stats as well. 
Currently I've got quite a few other projects running, but I'd love to help out in the development of this feature.
What's your current stance on genre support?

**Comment by Yooooomi** [comment]
Hello 👋 
The genres are currently stored in the database but the format is really hard to process to compute statistics on them. I guess one thing that could possibly help would be to group the sub genres into a bigger one. This will result in having like 20 different genres where now you easily have hundreds.

**Comment by CaptaiNiveau** [comment]
Yeah, makes sense. It'd still be interesting to see those special genres as well, even if they are stupid sometimes. Could be a hidden feature.
But the more interesting part are definitely the bigger genres. Spotify displays them in Spotify wrapped as well.
I think it's also useful, since it helps finding similar songs in a playlist related to the genre. That's what I'd like to use this feature for.
