### ISSUE TITLE
Favicon proposal

### ISSUE THREAD

**Issue by kimdre** [Yooooomi/your_spotify#107]
I'm really bad at making vectors (I wanted to make the magnifier transparent but I gave up lol) but here is my icon proposal.
It's the same green that Spotify uses.

<img src="https://user-images.githubusercontent.com/27567533/159956279-6744fb02-fb05-4384-8ae3-4fd249c958d6.svg" width="100"/> <img src="https://user-images.githubusercontent.com/27567533/159956279-6744fb02-fb05-4384-8ae3-4fd249c958d6.svg" width="25"/>

**Comment by Yooooomi** [comment]
I actually like it. It feels like it's not centered right?

**Comment by kimdre** [comment]
Yes you are right.
Here is a fixed version with transparency:

<img src="https://user-images.githubusercontent.com/27567533/160201346-4ae09973-4f61-4072-a13e-589409ae6aa4.svg" width="100"/> <img src="https://user-images.githubusercontent.com/27567533/160201346-4ae09973-4f61-4072-a13e-589409ae6aa4.svg" width="25"/>

**Comment by Yooooomi** [comment]
In the last release I use your favico, thanks a lot for this, it looks much better now :)
