### ISSUE TITLE
Feature: SSL Support

### ISSUE THREAD

**Issue by D4rkPh0en1x** [Yooooomi/your_spotify#109]
Hi
I installed your app yesterday and it looks very useful and great.
The only thing I don't like is that the web client doesn't have SSL support?
Isn't that possible with how you did the docker image? (sorry I'm new to all this...)
I saw that sometimes it's written about reverse proxy which I never used till now (so I need to read further about this) but as I have many docker images running just on different ports... I'm not sure if that would work that great...
Thanks for some info about that and thanks for your great work ;)

**Comment by D4rkPh0en1x** [comment]
Yeah but a direct integrated possibility would be nice?

I tried with swag (reverse DNS) to get it to work but unfortunately I just come to the login window and than I turn in a loop… Simply can’t login…
Need to check what I need to change :/

By the way a setting to set the default display time would be great instead of always the last 24 hours… Maybe I’m also just missing a point, like I sait I’m new to this…

**Comment by Yooooomi** [comment]
Unfortunately I don't think I want to implement SSL for now as it would just raise the number of issues you can get from setting up the project. Since I don't have much spare time I won't implement SSL. However, you can relatively easily set it up using something like nginx.
Having a default time span is a good idea however. I'll think about it next time I work on your Spotify.
Thanks for your feedback, feel free to open any issue if you get stuck setting up the project.

**Comment by wgetgoose** [comment]
> I tried with swag (reverse DNS) to get it to work but unfortunately I just come to the login window and than I turn in a loop… Simply can’t login… Need to check what I need to change :/

I also have this issue when using a reverse proxy. I think passing headers to the program might be the issue (see [this](https://github.com/thedevs-network/kutt/wiki/NGINX-config) nginx.conf from kutt.it).

**Comment by D4rkPh0en1x** [comment]
Thanks @Yooooomi for the info...
@wgetgoose  yeah I simply can't get it to work for now...

Maybe @Yooooomi  can tell us if we need to pass a special header or not?
Or do I need to let pass the server part also trough the reverse proxy? For the moment this part is directly accessible trough domain A and my web part trough domain B (the reverse proxy one)
Maybe also server part needs to be localhost only in a reverse proxy configuration?

I tried with folder config or subdomain config and none worked... 
I'm very new to reverse proxy but this swag is very easy and it has many finished configuration files integrated for different apps so you can simply copy and use them for another app (it's nginx based).

If you have any idea @Yooooomi

**Comment by Yooooomi** [comment]
The nginx configuration is quite simple once you've set up ssl in another config file.

You can find the nginx configuration im using [here](https://github.com/Yooooomi/your_spotify/issues/27#issuecomment-795985690).
At first you can try without ssl and find a guide on how to enable ssl on nginx.

**Comment by D4rkPh0en1x** [comment]
Had to play a bit around but at the end I got it to work with reverse proxy :)
SWAG uses variables to set the domain, port etc but somehow that doesn't work for the /api/ location
I had to use the proxy_pass http://localip:localport/; so that it worked - still don't understand why but at least it works now :)
So I can now do my german tutorial video on how I installed it on my Synology with docker run and have the bonus to explain it with reverse proxy :)
Thanks for your help

**Comment by D4rkPh0en1x** [comment]
I gonna close it later on when I have pasted the config...
I have to this correctly at home - did all remotely now and that's not the best for copying configuration properly :/

**Comment by D4rkPh0en1x** [comment]
So here is my swag (nginx reverse proxy) config for a subdomain based use - This one finally worked as for the API I had to enter the full address as proxy_pass and couldn't use variables:

`server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name spotify.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;


	location /api/ {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
	proxy_pass http://192.168.178.20:8080/;
	}

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app yourservername;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }	
}`

**Comment by D4rkPh0en1x** [comment]
As GitHub changes the code to a not very readable text I post the file here...
Pay also attention that for the /api/ location you need a / at the of your proxy_pass as else it doesn't work :/


[your_spotify.subdomain.conf.txt](https://github.com/Yooooomi/your_spotify/files/8416702/your_spotify.subdomain.conf.txt)

**Comment by Yooooomi** [comment]
Thanks for your configs :)
