### ISSUE TITLE
Is repartition supposed to be repetition? 

### ISSUE THREAD

**Issue by of-mice** [Yooooomi/your_spotify#113]
All instances of the word "repartition" should be changed to repetition, unless repartition has another meaning I'm not aware of. Just a spelling/word use issue

**Comment by Yooooomi** [comment]
Repartition is in the sense of distribution, do you think it would be better to name it distribution?

**Comment by marcus-k** [comment]
Perhaps it may be a better wording. I spend a while trying to figure out what "Listening repartition over day" actually meant before turning to Google to figure it out.

**Comment by Yooooomi** [comment]
Fixed. If I forgot to fix some please open a new issue :)
