### ISSUE TITLE
ARM Docker Image

### ISSUE THREAD

**Issue by azoller1** [Yooooomi/your_spotify#114]
Not sure where to post this, but I am looking to add a docker image for ARM support. Kind of a noob with building docker images, but would this be feasible with your source?

Thanks.

**Comment by Yooooomi** [comment]
Hello, the image is already arm compatible. Do you have any issues setting it up?

**Comment by azoller1** [comment]
> Hello, the image is already arm compatible. Do you have any issues setting it up?

I meant arm32(v7l). I'll look into it

**Comment by Yooooomi** [comment]
If you want to support 32 bits OSes you will have to replace mongo with something else and that might be a huge task to tacle.

**Comment by Yooooomi** [comment]
You might want to check this one https://hub.docker.com/r/webhippie/mongodb

**Comment by azoller1** [comment]
> You might want to check this one https://hub.docker.com/r/webhippie/mongodb

Yeah I saw that one. Thanks!

**Comment by azoller1** [comment]
Ok, I got an image built for arm32v7! It is running now, just need to figure out my reverse proxy settings.

**Comment by akeslo** [comment]
> Ok, I got an image built for arm32v7! It is running now, just need to figure out my reverse proxy settings.

Mind sharing how you figured this out?
