### ISSUE TITLE
[Feature Request] Dark mode

### ISSUE THREAD

**Issue by marcstae** [Yooooomi/your_spotify#118]
Basically what the title says :)

**Comment by Yooooomi** [comment]
It's a good idea, but I don't know how scalable I made the application for it to be able to receive dark mode, I'll definitely take a look at this.

**Comment by Yooooomi** [comment]
Implemented in last release! Feel free to open an issue if you have any problem with it.

**Comment by marcstae** [comment]
Thank you! Seems to work fine, and thanks for the new features added in this release :D
