### ISSUE TITLE
[Feature Request] All button for date range

### ISSUE THREAD

**Issue by musicderp** [Yooooomi/your_spotify#119]
In addition to the last day, last week, last month, and last year buttons, I'd like to see an "all" button that would show stats across all time. Obviously, I can select the date range every time without too much trouble, but an "all" button would simplify this dramatically, especially since the date select is not persistent quite yet.

**Comment by Yooooomi** [comment]
Implemented in last release! Feel free to open an issue if there is a problem with it.
