### ISSUE TITLE
Protecting backend endpoint

### ISSUE THREAD

**Issue by musicderp** [Yooooomi/your_spotify#122]
I recently exposed my config to the internet for my friends to use, and in order to do that, I had to expose the backend to the internet as well as the website in order to get it to work. The front end obviously isn't a problem, I'm able to use httpauth and slap that on there to not have any issues. Unfortunately, I was unable to put any kind of security on the backend. I'm a little unsure as to what all can be done through the backend, if it's literally nothing and the only thing that can be seen is that little page that says "Hello !" then no worries at all, that's not a problem. Otherwise, I'd like to see some way to either authenticate connections, or deny anything that doesn't come from the frontend. I'll keep playing around with my caddy rules, it's possible I may be able to only allow ips that access it from my dns servers, but I'm a little incompetent and am unsure if that'll work.

Loving the app so far, especially the share feature!

**Comment by Yooooomi** [comment]
Hello!

As far as I know there is no need to add additional security to the existing app. Most of the backend routes are only available when logged in or using a shared link.

Also, you can disable new account creation through the settings panel.

Nothing else but the application is implemented. If you want features such as ip whitelisting I'm afraid you'll have to find a way with your reverse proxy configuration.

But keep in mind that if you disable registrations, there is nothing an unauthenticated user can do. The only accessible routes are:

- getting global preferences: indicates wether or not registrations are enabled
- /: returns Hello for health checks 

I hope I answered your question. :)

**Comment by musicderp** [comment]
Awesome, that's everything I needed to know! Thank you so much!
