### ISSUE TITLE
After a while, no data seems to be getting tracked

### ISSUE THREAD

**Issue by samip5** [Yooooomi/your_spotify#125]
**Describe the bug**
After weeks and weeks of running, and importing large history, it seems that it's no longer getting new data?

**Expected behavior**
I expect it to keep getting data.

**Additional context**
Using npm directly on host aka non-dockerized install.

**Screenshots**
<img width="1730" alt="Screenshot 2022-05-12 at 8 56 11" src="https://user-images.githubusercontent.com/1703002/168001825-1da10c7f-43d3-48b9-87a5-792bee5193bc.png">

**Comment by samip5** [comment]
P.S How do I fix this?

`[warn]  No user is admin, cannot auto fix database`

**Comment by Yooooomi** [comment]
Hello, I don't know how you got in this state but no user in your database is admin where there should be at least one.

Something happened with your database and I don't where it could come from.

Check if you can manually set your user admin in the database.

**Comment by samip5** [comment]
That's wierd af as previously it was in a wierd state without the any admin users:

```
ay 12 07:10:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:12:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:14:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:16:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:18:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:20:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:22:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:24:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:26:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:28:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:30:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:32:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:34:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:36:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:38:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:40:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:42:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:44:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:46:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:48:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:50:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:52:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:54:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:56:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 07:58:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
May 12 08:00:02 webapp-bullseye node[48890]: [info]  Starting loop for 1 users
```

Which then seems like it wasn't even trying to refresh songs, but after I fixed it in database, and re-run it (thus also running the migrations), it started to gather data again?

**Comment by samip5** [comment]
I feel like this is a bug if there's no admin users, it will choke on itself but not show any error?

**Comment by Yooooomi** [comment]
In docker, if the migration fails the server never starts so there is no possibility for this to happen.

**Comment by samip5** [comment]
> In docker, if the migration fails the server never starts so there is no possibility for this to happen.

There is, as not everyone has that luxury of Docker.

**Comment by Yooooomi** [comment]
I never said this was not a big. I was meaning that in the intended way, the server **cannot** start if the migration fails.
It happens to you because you either ran the server even if the migration failed, or that you unset yourself from being admin.

**Comment by Yooooomi** [comment]
Do you have any news about this?

**Comment by samip5** [comment]
Well, no? It started working again after having an admin user manually set in DB, and running the migration.

**Comment by Yooooomi** [comment]
I identified the problem. I'll comment again when solved.

**Comment by Yooooomi** [comment]
Should be fixed now
