### ISSUE TITLE
Bug: All option for stats causes certain graphs to not display any data

### ISSUE THREAD

**Issue by WahidBawa** [Yooooomi/your_spotify#128]
**Describe the bug**
When selecting the *All* option for time period of stats shown, a number of graphs fail to display any data

**Expected behavior**
I expect the graphs to draw out as usual when selecting any other time period.

**Additional context**
When I select the *All* option for time, it'll show a bunch of the graphs empty like this:
![image](https://user-images.githubusercontent.com/34203195/168455755-d316ddcd-ab70-4ebe-8d66-89b25aabf9ed.png)
You can see this for yourself [here](https://spotify.yoh.gay/all?gname=All&token=62a63998-c307-4572-8bfd-3878d9a85ecf)

In contrast, when I set a manual time period using the gear icon for the time span the *All* option would use, it displays them just fine like this:
![image](https://user-images.githubusercontent.com/34203195/168455834-1ed05f29-3d3e-4d4c-9bae-d8f91a4f0e26.png)
You can see this for yourself [here](https://spotify.yoh.gay/all?gtype=custom&gstart=Tue+Jan+01+2019+00%3A00%3A00+GMT-0500+%28Eastern+Standard+Time%29&gend=Tue+May+31+2022+23%3A59%3A59+GMT-0400+%28Eastern+Daylight+Saving+Time%29&token=62a63998-c307-4572-8bfd-3878d9a85ecf)

Looking at the logs I see the issue here. When the *All* option encompasses multiple years, it still splits the time by months instead of individual years, and that's why I think it's bugging out. You can take a look at the screenshots below for this.

When using the *All* option: 
![image](https://user-images.githubusercontent.com/34203195/168455922-1a7b3a5b-dec4-47a9-9969-681d7adcd566.png)

When using the manual time period:
![image](https://user-images.githubusercontent.com/34203195/168455938-abf219a6-38e7-4cb2-bb13-6d1395913f2a.png)

So it looks like the fix shouldn't be too complicated if all is as it seems, just gotta change that based on the span of *All*. 

Thanks for the sharing with friends feature btw, it should make it easier to see my issue here. 

Thanks again.

**Comment by WahidBawa** [comment]
Just wanted to add that the issue is present on the home page as well
![image](https://user-images.githubusercontent.com/34203195/168497737-4106b9b1-ed63-4920-ae58-832cd41cfd6d.png)
As seen [here](https://spotify.yoh.gay/?gname=All&token=62a63998-c307-4572-8bfd-3878d9a85ecf)

**Comment by Yooooomi** [comment]
Hello there!

This is a weird bug. I just checked, you have your first listened data in August 2020, which seems pretty right. The timesplit being month in the request is not the source of the bug since YourSpotify will request monthly-split data for range less than 2 years. I'll check this a bit later but this sure is a bug. Thanks for reporting it.

PS: Very nice idea to use the shared link to share the bugs you are facing, 5Head move.

**Comment by Yooooomi** [comment]
Should be fixed now 🎉

**Comment by WBawa** [comment]
Just updated, looks like everything is working. 

Thanks for the quick response!
