### ISSUE TITLE
Upgrading Instructions

### ISSUE THREAD

**Issue by JakeyPrime** [Yooooomi/your_spotify#129]
New update looks great, but tried a pull and rebuild and I seem to be stuck on the old version, any chance you can update the readme to include upgrade instructions? 

Cheers!

**Comment by WahidBawa** [comment]
When I updated the image using docker-compose I followed the following steps.

```bash
docker-compose down
docker-compose pull
docker-compose up -d
```

Try that and see if you get any difference.

**Comment by JakeyPrime** [comment]
> When I updated the image using docker-compose I followed the following steps.
> 
> ```shell
> docker-compose down
> docker-compose pull
> docker-compose up -d
> ```
> 
> Try that and see if you get any difference.

Yep, this did it for me, weird, thank you so much!
