### ISSUE TITLE
[Client] RangeError: Invalid time value

### ISSUE THREAD

**Issue by zphw** [Yooooomi/your_spotify#135]
**Describe the bug**
Choosing "all" interval will yield the "RangeError: Invalid time value" error in console.

**Expected behavior**
Displays all results available.

**Comment by Yooooomi** [comment]
Hello!
When did you start using YourSpotify? 
Do you have any knowledge in using mongo?

Also, if that's not too private, would you be able to share a shared link so that I can experience the issue?

Thanks

**Comment by zphw** [comment]
Hi there,

I just started using it yesterday, and, yes, I'm familiar with mongo.

My instance is at [https://your-spotify.zph.io/?gname=Last+day&token=19ec58e6-40b9-45eb-a5cb-c5197ccac74b](https://your-spotify.zph.io/?gname=Last+day&token=19ec58e6-40b9-45eb-a5cb-c5197ccac74b), and you may click "All" there to reproduce this issue.

Thanks,

**Comment by Yooooomi** [comment]
Thanks for sharing the link, you can now change it in the settings so that it is not valid anymore. The issue is that when you create an account, it does not seems to initialize your first data timestamp. I'll take a look at this since it's a pretty strong bug. Thanks for the feedback
