### ISSUE TITLE
Add user feedback/alert when trying to play track with no active device.

### ISSUE THREAD

**Issue by seanecoffey** [Yooooomi/your_spotify#136]
**Describe the bug**
Very minor - not really a bug.  When pressing play button on a song with no active spotify device, the user should receive input that there is no active device.

**Expected behavior**
Trigger alert message (presumably, alertMessage) that there is no active device.  Else trigger web player or similar.

**Additional context**
The server receives and logs this response from Spotify.
```
[error]  {

  error: {

    status: 404,

    message: 'Player command failed: No active device found',

    reason: 'NO_ACTIVE_DEVICE'

  }

}
```
Could add something like this to the play route error handler, before line 56 (routes/spotify.ts):
`if(e.response.data.error.reason==="NO_ACTIVE_DEVICE") { return {ALERTMESSAGE CONFIG} }`

And then add alertMessage to the error handler in the Track constructor?

I may look at this and try and PR if time permits.

**Comment by Yooooomi** [comment]
Will definitely do! Thanks for the feedback

**Comment by Yooooomi** [comment]
Added!
