### ISSUE TITLE
General artist-stats performance

### ISSUE THREAD

**Issue by skrollme** [Yooooomi/your_spotify#162]
Since I do not know if it is just my (not that powerful) server and/or docker-setup or a general topic I did not start with a bug-ticket. 

I'm very happy with _your-spotify_ and was even more happy, when I got my full export from Spotify and got it imported in _your-spotify_. But with this large set especially the artist's stats-page takes very long to load.

An example:
I use the search on the top/left and I get the name (and image) of the artists I searched for almost immediately. But when I click the artist it takes around 50sec for the page to finish loading for - in this case - the artist with rank 60 which has around 150 listening-entries. 

Other pages, like homepage-stats for last year (with 5721 songs listened) load in about 5sec which I'm totally fine with.

Here a some metrics of the database, which I think can be helpful to compare if it is just my setup or the application in general.

| Table  | Row count |
| ------------- | ------------- |
| albums  | 22251 |
| artists | 14226 |
| infos | 73172 |
| tracks | 35814 |

**Comment by skrollme** [comment]
Ah ok, makes sense. Thank you for the feedback.

Could a possible solution for this be, to queue the artist's rank-calculation to let it run in the background over the day? Or maybe in a nightly cron on a customizable base (daily, weekly, monthly)?

**Comment by Yooooomi** [comment]
Should be fixed in last release.

**Comment by skrollme** [comment]
Hello @Yooooomi and thanks for letting me know.
I already updated the app in my docker-setup but - to be honest - I see no difference in loading times. I picked a random artist (150 listens) page which took around 40seconds (`/artist/*/stats`). Immediately after the page has loaded, the rank (which was 68 for this artist) was loaded asynchronously. This `/artist/*/rank` call took 6sec. 
I will later check how the server-performance (cpu, ..) behaves during the loading

**Comment by Yooooomi** [comment]
Mmh, sad news. Since artist stats cannot be customized with time, I should compute them on backend and only fetch the result from the front end. This logic is new in the Spotify backend. I'll try to implement something like this in the next release. The main point is I don't want to compute artist stats for artists you'll never see.
I'll think about it. Sorry for the hope.

**Comment by skrollme** [comment]
No problem, and no need to say sorry 😄 I'm very grateful for the great tool you created and happy that you continue working on it 👍

**Comment by jamess60** [comment]
Tip - Updating to a newer mongo version (5 or higher) massively increased performance for me

**Comment by quentinguidee** [comment]
Fixed by #348, #354 and #355 (release 1.8.0)
