### ISSUE TITLE
[Feature Request] Genre statistics

### ISSUE THREAD

**Issue by mafraqs** [Yooooomi/your_spotify#164]
Since the data for song genres is already available in the app, it would be cool to see some statistics on it.

E.g.
- Top Genre -> With number and runtime per genre
- Genre page -> Same as the artists page, but also shows
    - artists one has listened to that have music for that genre
    - albums one has listened to in that genre

However, there are probably thousands of sub-genres per genre, which might make the whole thing quite difficult, unless spotify provides the paren/child genre information.

The app is fantastic btw - really enjoy using it! _(even though i'm having some problems but that is a topic for another issue)_

**Comment by Yooooomi** [comment]
Hello! Sorry for not coming back to you. As explained in #104, I'm not planning on working on this in the near future as it involves a lot of work for such a feature to make any sense in the actual state of the app.
