### ISSUE TITLE
Docker related question (not answer on Google)

### ISSUE THREAD

**Issue by Systematic01** [Yooooomi/your_spotify#165]
I just tried to setup the panel for Spotify using the guide located at [Breadnet](https://breadnet.co.uk/your-spotify-2022/). Everything went well except one thing, as soon as I type 'docker-compose up -d' it starts loading but ends up with "ERROR: Service 'web' failed to build : Build failed". Any solutions on this? Google only gives me solutions from years ago that do not work in my case. 

Screenshot below:
![image](https://user-images.githubusercontent.com/72387613/198831250-5a04bd9d-4430-4715-a49e-3ec32e064492.png)

**Comment by samip5** [comment]
I don't think running on Windows is quite supported.

**Comment by Yooooomi** [comment]
Hello, my advice would be to use the prebuilt image and not build your own. If you use the `your_spotify_server` and `your_spotify_client` you should not need to build the image from scratch. Use the docker-compose file in the README and it should work.

**Comment by Systematic01** [comment]
> Hello, my advice would be to use the prebuilt image and not build your own. If you use the `your_spotify_server` and `your_spotify_client` you should not need to build the image from scratch. Use the docker-compose file in the README and it should work.

Thanks this solved the problem I was facing.
