### ISSUE TITLE
Date selector isn't fully visible when using a phone

### ISSUE THREAD

**Issue by samip5** [Yooooomi/your_spotify#172]
**Describe the bug**

The date selector is not fully inside it's box.

**Expected behavior**

I would have expected it to be properly handled.

**Screenshots**

![Screenshot_20221203-104157.png](https://user-images.githubusercontent.com/1703002/205432575-bba516da-ae66-4a3e-aa4e-b824d3e3458f.png)

**Comment by Yooooomi** [comment]
Hello. Thanks for the report! I have a bit of work for mobile still. There are places where the app is not displayed. I'll keep this in mind when working on the project next time.

**Comment by Yooooomi** [comment]
Should be fixed in last release.
