### ISSUE TITLE
[Question] How do I create a new user?

### ISSUE THREAD

**Issue by NeoHBz** [Yooooomi/your_spotify#173]
I tried enabling "Allow new registrations" and logging in with a new account and I got the "User not registered in the Developer Dashboard" error on the server backend.

So as the title says, How do create a *new* user?

**Comment by Yooooomi** [comment]
Hello, it feels like this error comes from Spotify. Can you post your configuration files?

**Comment by NeoHBz** [comment]
> Hello, it feels like this error comes from Spotify. Can you post your configuration files?

version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=https://spotifyserver.mytld.com
      - CLIENT_ENDPOINT=https://spotifystats.mytld.com
      - SPOTIFY_PUBLIC=<public_token>
      - SPOTIFY_SECRET=<secret_token>
      - CORS=all
      - TIMEZONE=Asia/Kolkata
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=https://spotifyserver.mytld.com

how do I add PUBLIC and SECRET of another user apart from the admin, or is that not required to create a new user at all?

**Comment by NeoHBz** [comment]
> Can you double check that your credentials are right?

My admin account works flawlessly.

**Comment by Yooooomi** [comment]
Hello, sorry for not coming back to you, any news on this?

**Comment by TheDoplerEffect** [comment]
> > Can you double check that your credentials are right?
> 
> My admin account works flawlessly.

Just add new user mail(spotify registration) in "user and access" on developer.spotify.com it works for me

**Comment by NeoHBz** [comment]
> Just add new user mail(spotify registration) in "user and access" on developer.spotify.com it works for me

apparently, I was missing this. Thanks.

Image for future reference:
<img width="1440" alt="Screenshot 2023-01-17 at 12 36 59 PM" src="https://user-images.githubusercontent.com/56602090/212832416-726d6740-270a-4d51-ac27-006d48781776.png">
