### ISSUE TITLE
Shown blank page with Hello when docker-compose port is changed

### ISSUE THREAD

**Issue by palzino** [Yooooomi/your_spotify#174]
I have changed the port 3000 to 3500 as grafana uses the 3000 port, Now when I go to localhost:8080 it shows a blank white screen with hello! and localhost:3500 gives a connection reset. I have tried docker-compose build after changing the yml to no effect.

**Comment by Yooooomi** [comment]
Hello, can you share your compose file please?

**Comment by palzino** [comment]
`  GNU nano 6.2                                                                                                  docker-compose.yml *                                                                                                         version: "3"

services:
  app:
    container_name: express-mongo
    restart: always
    build:
     context: ./server
     dockerfile: Dockerfile.production
     args:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - API_ENDPOINT=http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard
      - CLIENT_ENDPOINT=http://localhost:3500
      - SPOTIFY_PUBLIC=
      - SPOTIFY_SECRET=
      - CORS=all
      #- MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify

  mongo:
    container_name: mongo
    image: mongo:4.4.8

  web:
    container_name: web
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.production
      args:
        - NODE_ENV=production
    ports:
      - "3500:3500"
    environment:
      - API_ENDPOINT=http://localhost:8080



`
Is my attached docker-compose.yml, I removed my keys for the purpose of this post

**Comment by Yooooomi** [comment]
Hello, don't change the target port inside the container, your syntax should be 3500:3000.
