### ISSUE TITLE
Are graphs using UTC time?

### ISSUE THREAD

**Issue by Death-Pact** [Yooooomi/your_spotify#179]
**Describe the bug**

Graphs using UTC time. 

**Expected behavior**

Graphs should use a selected time zone.

**Additional context**

there doesn't seem to be a way to change the time zone of the containers using environmental variables. Or at least I haven't seen any documentation on it. Small creature comfort, but it would be nice to have my time zone be utilized in the app. Also, I could just be wrong and the import data could be incorrect? See below screen shot taken of my instance. I never listen to music at 0300 to 0400. Yet it shows in my bottom chart.

![image](https://user-images.githubusercontent.com/85306178/209419877-12aaaa4c-4df8-4f37-a6df-cfba0913df86.png)

Thanks for making a great app! Hopefully, I am just wrong and just don't understand the graph.

**Comment by andrewtwelch** [comment]
Yeah I'm seeing this too, graphs are 10 and a half hours out, which corresponds with my time zone (+10.5)

**Comment by andrewtwelch** [comment]
@Death-Pact actually just found an older issue about this, #169.

**Comment by Death-Pact** [comment]
@andrewtwelch dang. Forgot to check the closed issues... well that was a quick fix! Thanks a lot for the quick reply. I knew I was missing something small. Its all fixed now.
