### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by TheDoplerEffect** [Yooooomi/your_spotify#180]
Hello,is it possible to set the time zone for each specific user? in web settings for example, not in docker env.
we use the service in two and our difference in time zones is 4 hours, and i set my friend's timezone in docker env, so my listening charts("Time listened") have offsets of 4 hours, this is not very convenient. But in the listening history("Your history") it shows my timezone
![firefox_Mqx0MOpD5Z](https://user-images.githubusercontent.com/3193245/209569810-c46354f5-a177-4696-87e0-1147d99018fd.png)
![firefox_h1O5r29rdN](https://user-images.githubusercontent.com/3193245/209569812-0701d027-cd3f-450f-b694-6e404d29419a.png)

**Comment by Yooooomi** [comment]
Hello, it's not possible yet. I can see something where you can edit your timezone from default to a specific one in the settings. Thanks for the feedback

**Comment by Yooooomi** [comment]
Should be fixed in last release.
