### ISSUE TITLE
[Question] Backup and restore database

### ISSUE THREAD

**Issue by demetera** [Yooooomi/your_spotify#181]
Would be useful for users, who are not (yet) familiar with docker, how to backup accumulated data in Mongo database (if I need to move/reinstall server), or do I have to request data from Spotify?

As I understand, technically it can be achieved by bringing old Mongo container to the new environment, but maybe someone could help with exact docker commands in this case.

Thank you

**Comment by Yooooomi** [comment]
Hello! The only way now is to backup the volume of the mongo container. Either by mounting a directory like in the example or to create a docket volume.
