### ISSUE TITLE
Cant authenticate with Spotify

### ISSUE THREAD

**Issue by Soundz1337** [Yooooomi/your_spotify#182]
I followed [this guide](https://breadnet.co.uk/your-spotify-2022/) but cant seem to get this working.

![firefox_VeQU06sgmd](https://user-images.githubusercontent.com/43936650/211041929-9c57e78a-2188-4c67-acc0-cd7f23c86fb6.gif)

![firefox_QfO2EIxUA8](https://user-images.githubusercontent.com/43936650/211042353-d89d7080-3f60-4ab2-838f-6216a0b311dd.png)

![firefox_DdNhyWMuQ3](https://user-images.githubusercontent.com/43936650/211042427-10dfa1ca-b220-4889-ac7b-5096c9b13a15.png)

**Comment by makanimike** [comment]
I have this too. It worked fine the first day of installation and when I reinstalled from scratch a few weeks ago. Just took troubleshooting this up again today.
  
From reading some other threads about similar errors, I wonder if you have this installed on a machine or VM that also runs other services? I think your_spotify might be susceptible to other docker containers or services conflicting with it.

**Comment by Soundz1337** [comment]
> I have this too. It worked fine the first day of installation and when I reinstalled from scratch a few weeks ago. Just took troubleshooting this up again today.
> 
> From reading some other threads about similar errors, I wonder if you have this installed on a machine or VM that also runs other services? I think your_spotify might be susceptible to other docker containers or services conflicting with it.

Im running it on unraid. Not sure if its conflicting with anything. I got really rusty and started redoing my whole server this week.

**Comment by Yooooomi** [comment]
Hello! The API_ENDPOINT should be localhost:8003 since this is the port bound on the host :)

**Comment by makanimike** [comment]
though i am not OP, I did have the exact same docker-compose file (at least for a while during my lengthy troubleshooting). port 8003 did not fix it. Where would that come from? is there something hardcoded outside of the docker compose file?  
  
FWIW, I have it working again. The conflict in my case was port 8080. I had my instance running on a VM alongside scratch_map. That app also used port 8080. My best guess is that scratch map was prioritized.  
I moved your_spotify to port 8085 and I replaced all 'localhost' reference to the actual IP. Both in the docker compose file, as well as in the spotify dev page.  
 
It is working now. But I a bit sceptical for the time being until it stays accessible for a few days :) It had worked twice before for a day before it just decided to stop working a day later....

**Comment by Soundz1337** [comment]
> though i am not OP, I did have the exact same docker-compose file (at least for a while during my lengthy troubleshooting). port 8003 did not fix it. Where would that come from? is there something hardcoded outside of the docker compose file?
> 
> FWIW, I have it working again. The conflict in my case was port 8080. I had my instance running on a VM alongside scratch_map. That app also used port 8080. My best guess is that scratch map was prioritized. I moved your_spotify to port 8085 and I replaced all 'localhost' reference to the actual IP. Both in the docker compose file, as well as in the spotify dev page.
> 
> It is working now. But I a bit sceptical for the time being until it stays accessible for a few days :) It had worked twice before for a day before it just decided to stop working a day later....

Could you attach a screenshot of your settings please? Still having some trouble

**Comment by Yooooomi** [comment]
@Soundz1337 did you change your compose file as I suggested? If yes, can you please post them again?

**Comment by makanimike** [comment]
> Could you attach a screenshot of your settings please? Still having some trouble

sure. but, as I feared, it did not survive a reboot. I am back at square one.
  
![image](https://user-images.githubusercontent.com/88232673/211208342-22f9b914-d829-4757-bd42-4313f9fcf92a.png)

**Comment by Yooooomi** [comment]
>  > Could you attach a screenshot of your settings please? Still having some trouble
> 
> 
> 
> sure. but, as I feared, it did not survive a reboot. I am back at square one.
> 
>   
> 
> ![image](https://user-images.githubusercontent.com/88232673/211208342-22f9b914-d829-4757-bd42-4313f9fcf92a.png)
> 
> 

Your configuration is fine. Everything happening is caused by your device. Your local ip may have changed. Your container might not have reboot since the mongo container is not flagged as restart: always

**Comment by makanimike** [comment]
I think flagging mongo to restart: always fixed it for me (not OP). At least it is working today, after the first reboot since that modification! :)  
(my IP is fixed)

**Comment by makanimike** [comment]
it came back yesterday. I didn't change anything.
I noticed yesterday had a new release, so I updated. But I still get the global preferences issue again when logging into spotify.

**Comment by Soundz1337** [comment]
> You access your web page using 192.168.2.229, but your API_ENDPOINT is set to localhost. This means it tries to reach your computer. You might want to set the API_ENDPOINT to 192.168.2.229:8080 and the CLIENT_ENDPOINT to 192.168.2.229:3000

Sorry for the long wait. I already tried that, but no luck. Any other ideas I could try out?

**Comment by Yooooomi** [comment]
Can you omit the cors in your configuration? I bugged them in the last release.

**Comment by skyajal** [comment]
Omitting cors allowed mine to start working again.

**Comment by Soundz1337** [comment]
> Can you omit the cors in your configuration? I bugged them in the last release.

I haven't tried tbh. I saw that linuxserver made a unraid template and now I got it to work. 

Thanks for all the support!
