### ISSUE TITLE
Change default project description

### ISSUE THREAD

**Issue by Steeven9** [Yooooomi/your_spotify#185]
**Describe the bug**

The page metadata have the default `Web site created using create-react-app` meta description tag, which albeit being extremely minor and not impacting functionality in any way is... not looking great when the link is embedded somewhere like Discord (see attachment).

**Expected behavior**

A non-default description, such as `A self hosted Spotify tracking dashboard` or something similar.

**Additional context**

Happens with the latest version (1.3.2). The change can be made in [public.html](https://github.com/Yooooomi/your_spotify/blob/fc31ae7516e22bd0b6a0ef951f5228b4baed1724/client/public/index.html#L10)

**Screenshots**

![image](https://user-images.githubusercontent.com/25285679/211218746-f2b87f90-98d0-4f4c-b651-daf65ae765fd.png)

**Comment by Yooooomi** [comment]
Hello! You're right, I could make this a lot cleaner. Will definitely look into this for the next release.

**Comment by Yooooomi** [comment]
Should be fixed in last release.
