### ISSUE TITLE
Unable to open settings page after latest update

### ISSUE THREAD

**Issue by allquiet-hub** [Yooooomi/your_spotify#19]
I can open the main page, stats and history as well. When i try to open the settings page, i get only a gray page.

**Comment by Yooooomi** [comment]
Hello, nice to see you!
The problem only occurs if you access the settings page after logging in. Of course this is not intended and I fixed it in my latest push, new release should be available on dockerhub in a few minutes [here](https://hub.docker.com/repository/docker/yooooomi/your_spotify_client)
Let me know if I can close this afterwards

**Comment by allquiet-hub** [comment]
You said that the new docker image would be of "yooooomi/your_spotify_client", but only "yooooomi/your_spotify_server" got updated. Did you mistype or do I have to wait a bit more for it to be online?

**Comment by Yooooomi** [comment]
You might have been a bit early: https://hub.docker.com/repository/docker/yooooomi/your_spotify_client

**Comment by allquiet-hub** [comment]
Thanks a lot, it is solved now!
