### ISSUE TITLE
[Feature Request] Blacklist Artist

### ISSUE THREAD

**Issue by Byolock** [Yooooomi/your_spotify#192]
I have an artist which does produce commedy and splits his live acts into ~2 minute parts. As his live acts are around 90 minutes long just watching 2 of these accounts for many plays and minutes played therefore leading to top postition in many statistics. As this is not music and rather special I would like to exclude this artist. In some statistics, it is easy to ignore, in others though like the "Artist listening distribution" its harder to see what it would look like without that artist.

Although I know a few commedy artists which do this I dont know if this is common or not, so maybe thats a rather special use case. If blacklisting an artist is a complex feature to implement for such a rare case I totally understand.

**Comment by Yooooomi** [comment]
Hello! Interesting issue we have here!
Would blacklisting an artist, deleting existing records and never recording them again be fine for you?

**Comment by Byolock** [comment]
Yes that would be fine.

**Comment by NeoHBz** [comment]
> Hello! Interesting issue we have here! Would blacklisting an artist, deleting existing records and never recording them again be fine for you?

Hi, maybe not "delete" the existing records and continue recording them, just not count the artist on the stats page, so if the user later removes the artist  from the blacklist, the tracking data remains normal?
