### ISSUE TITLE
not able to authorise spotify, also this global preferences error

### ISSUE THREAD

**Issue by QuantaNeon** [Yooooomi/your_spotify#196]
![image](https://user-images.githubusercontent.com/84242952/215541712-2680c248-14e1-4c90-bcf1-e016cea379c1.png)
![image](https://user-images.githubusercontent.com/84242952/215542744-e2b030dc-7c3b-4934-9269-ffeb1e232371.png)

[Screencast from 30-01-23 10:22:10 PM IST.webm](https://user-images.githubusercontent.com/84242952/215542062-42ff021a-7f48-487d-a79c-e21e7e7d3da6.webm)

> version: "3"
> 
> services:
>   server:
>     image: yooooomi/your_spotify_server
>     restart: always
>     ports:
>       - "8080:8080"
>     links:
>       - mongo
>     depends_on:
>       - mongo
>     environment:
>       API_ENDPOINT: http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard
>       CLIENT_ENDPOINT: http://localhost:3000
>       SPOTIFY_PUBLIC: 
>       SPOTIFY_SECRET: 
>       CORS: http://localhost:3000,http://localhost:3001 # "all" if you want to allow every origin
> 
>   mongo:
>     container_name: mongo
>     image: mongo:4.4.8
>     volumes:
>       - ./your_spotify_db:/data/db
> 
>   web:
>     image: yooooomi/your_spotify_client
>     restart: always
>     ports:
>       - "3000:3000"
>     environment:
>       API_ENDPOINT: http://localhost:8080

yourspotify logs does say this, so seems like it logged in butttt idk whats happening
![image](https://user-images.githubusercontent.com/84242952/215543774-cee9566a-ed95-4f7c-9839-ef951bab6c2a.png)

**Comment by Yooooomi** [comment]
I'll fix this next week. For now just remove the CORS env variable

**Comment by QuantaNeon** [comment]
umm what do you mean by remove it, just make that line disappear?

**Comment by QuantaNeon** [comment]
alr i set cors to all and now it works fine
