### ISSUE TITLE
need help with setting yourspotify up using cloudflare tunnels

### ISSUE THREAD

**Issue by QuantaNeon** [Yooooomi/your_spotify#197]
everything works fine locally, but i want to be able to access it from anywhere, this is the server
![image](https://user-images.githubusercontent.com/84242952/215670435-6cfc20b0-52d4-4067-a8b9-fcd5a0cd9176.png)

and this is on my pc
![image](https://user-images.githubusercontent.com/84242952/215657874-deab6658-2264-43ca-8619-64839d293f04.png)

i am using cloudflare tunnels

**Comment by Yooooomi** [comment]
Hey, I cannot help you as is. Please give me some config files, logs, etc.

**Comment by QuantaNeon** [comment]
![image](https://user-images.githubusercontent.com/84242952/216681309-eb584396-d66a-4ee3-8c4d-79e91f9fc511.png)
![image](https://user-images.githubusercontent.com/84242952/216681394-b13fe019-1e6f-450e-954c-3a91f645018c.png)
![image](https://user-images.githubusercontent.com/84242952/216683703-748ddbf7-dc70-46eb-9b15-deb18446785c.png)

[hmlog.log](https://github.com/Yooooomi/your_spotify/files/10581856/hmlog.log)

**Comment by QuantaNeon** [comment]
as i said stuff work fine locally, jus wanna access outside the linux server

**Comment by Yooooomi** [comment]
You can't set localhost here as a value. Localhost from cloud flare point of view means nothing. It expects a public ip.

**Comment by michaelkennethdavid** [comment]
In addition to what Yoooomi said, you need to tunnel port 3000 and 8080.

Here's my config:

![image](https://user-images.githubusercontent.com/55848461/216753169-287fb993-a97c-4414-b6b5-2a01426a0391.png)

![image](https://user-images.githubusercontent.com/55848461/216753273-65e7cace-154d-47a7-822c-ced01e4ac2e4.png)

![image](https://user-images.githubusercontent.com/55848461/216753341-6db243b4-b0a0-4a38-b90e-888f39703de7.png)

![image](https://user-images.githubusercontent.com/55848461/216753528-56fcf82b-8bfe-4e4c-83ae-cadd687cd2bc.png)

**Comment by QuantaNeon** [comment]
@michaelkennethdavid
heres my updated comfig..why does clickong on login with spotify
![image](https://user-images.githubusercontent.com/84242952/216763882-65a1c6a1-ba99-462a-98bd-85252abc720b.png)
take me to http://localhost:8080/oauth/spotify

heres the config
![image](https://user-images.githubusercontent.com/84242952/216763904-c9245ee2-98e3-4f17-a77f-1ed0d5102134.png)
![image](https://user-images.githubusercontent.com/84242952/216763907-4149712d-2437-41e2-9ddd-9da757cfde67.png)

heres the cloudflare tunnel
![image](https://user-images.githubusercontent.com/84242952/216763931-cf7d0227-dc01-4be6-a5d6-8bf0e16d8bd1.png)

**Comment by michaelkennethdavid** [comment]
Maybe it is cached. Try opening in Incognito, or try purging the cache in Cloudflare

**Comment by QuantaNeon** [comment]
> Maybe it is cached. Try opening in Incognito, or try purging the cache in Cloudflare

![image](https://user-images.githubusercontent.com/84242952/216764751-de415189-6c70-4e1e-9161-d3f32b718638.png)
hm why does it do that..

**Comment by michaelkennethdavid** [comment]
How did you end up with that URL?

**Comment by QuantaNeon** [comment]
clicked on login with spotify

**Comment by michaelkennethdavid** [comment]
`https://accounts.spotify.com/en/authorize?response_type=code&client_id=[CLIENT_ID]&scope=user-read-private%20user-read-email%20user-read-recently-played%20user-modify-playback-state%20playlist-modify-private%20playlist-modify-public&redirect_uri=https://spotify-api.quantaneon.com/oauth/spotify/callback`

The auth params to Spotify looks good, so I don't know why you end up with that URL after logging in.

**Comment by QuantaNeon** [comment]
no not after logging in
i havent logged in yet ig

**Comment by QuantaNeon** [comment]
![image](https://user-images.githubusercontent.com/84242952/216765957-3afdfc01-d1f2-4e6c-98db-a1354a83a23b.png)
even when i manually remove the shaded part and log in there...
it goes back to saying this 
![image](https://user-images.githubusercontent.com/84242952/216765986-7a00c875-3b81-4901-a7c6-349a86a4de74.png)

**Comment by michaelkennethdavid** [comment]
Just making sure, are you using this link to access your site? `https://spotify.quantaneon.com`

**Comment by QuantaNeon** [comment]
yes

**Comment by QuantaNeon** [comment]
idk how..but just works now...it was prolly cache
