### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by kpwenzel** [Yooooomi/your_spotify#198]
OK, I'm bashing my head against the wall with this. I've checked every issue related to my problem with no avail. I have to be missing something here. 

Docker: 
```version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://10.297.25.184:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://10.197.25.184:3000
      SPOTIFY_PUBLIC: <client id>
      SPOTIFY_SECRET: <client secret>
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://10.197.25.184:8080
```
Spotify Dashboard: 
![image](https://user-images.githubusercontent.com/25330492/216109396-fe1919ac-db82-4c05-8918-706cef96dc17.png)

Issue: 

https://user-images.githubusercontent.com/25330492/216111738-e704f4bc-f413-4e35-b3d5-6d4779871e4a.mp4

**Comment by Yooooomi** [comment]
Hello, it seems that you mistyped the 197 or 297 part of your ip.

**Comment by kpwenzel** [comment]
Well would you look at that. Thanks so much, that ended up fixing it.
