### ISSUE TITLE
MongoDB authentication

### ISSUE THREAD

**Issue by Butzlabben** [Yooooomi/your_spotify#2]
Hi,
I really like this project, but there is a security concern. If you start all containers normally, the mongoDB can be accessed without any credentials, even from a remote location. So there should be an option in the docker-compose.yml to set some credentials for the app.

**Comment by Yooooomi** [comment]
Nice point!

Fixed in c961b0e. Now only linked docker can connect to the database (at least when following the example `docker-compose` file)
