### ISSUE TITLE
I can't see my recently played songs

### ISSUE THREAD

**Issue by michaelkennethdavid** [Yooooomi/your_spotify#202]
**Describe the bug**

After updating to the latest version (v1.5.0), recently played songs are not added in the "Your History" section.

**Expected behavior**

Recently played songs are added in the "Your History" section.

**Additional context**

Steps to Reproduce:

1. Listen to several songs on Spotify.
2. Wait for a few minutes.
3. Observe that the logs display the message "Refreshing songs for your_username."
4. Refresh the app, but notice that the song is not visible in the "Your History" section.

Workaround:

1. Navigate to the settings and block an artist.
2. Unblock the same artist.
3. You will now be able to see the previously missing songs.

I think the reason for this is the presence of `blacklistedBy: []`, which causes the `info` to not be included in the query results.

```
{
    _id: ObjectId('63e75592930c864378bf3909'),
    owner: ObjectId('63e74285b2c43793e38c7b53'),
    id: '3TxnGSedv9ZKBFtiC0li1z',
    played_at: ISODate('2023-02-11T08:43:36.982Z'),
    blacklistedBy: [],
    __v: 0
}
```

**Comment by Yooooomi** [comment]
What did I do 🤦. I'm checking this. Sorry for the stupid mistake

**Comment by Yooooomi** [comment]
Should be fixed now :)
