### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI when logging to Spotify (unRAID)

### ISSUE THREAD

**Issue by rh535** [Yooooomi/your_spotify#204]
I am running into "INVALID_CLIENT: Invalid redirect URI" when I try to login for the first time. I have included my unRAID docker config screenshot and my Spotify dev settings. 

The URL when I click login" `https://accounts.spotify.com/authorize?response_type=code&client_id=MY NUMBER *********&scope=user-read-private%20user-read-email%20user-read-recently-played%20user-modify-playback-state%20playlist-modify-private%20playlist-modify-public&redirect_uri=http%3A%2F%2F192.168.1.11%3A2392%2Fapi%2Foauth%2Fspotify%2Fcallback`<a href="https://imgur.com/IoG5UMN"><img src="https://i.imgur.com/IoG5UMN.png" title="source: imgur.com" /></a>

<a href="https://imgur.com/XRfCXZ4"><img src="https://i.imgur.com/XRfCXZ4.png" title="source: imgur.com" /></a>
I can't wait to get this up and running. Thanks for the great app

**Comment by garrettmueller** [comment]
Same issue here was well. Unraid didn't like that my HTTPS port was 443 even though no other dockers are using it so I changed to 442.

I have my servers local host name (I don't use the IP or local host I have it set as a name in the unraid settings)

Do I need to use the IP?

**Comment by GossamerSolid** [comment]
Same issue here.

I'm using an external accessible IP for my callback and I still get the error.

**Comment by Yooooomi** [comment]
Hello, as we can see in the url you have, linuxserver is expecting /api/oauth/spotify/callback. I think just adding the api prefix should fix the whole thing.

**Comment by GossamerSolid** [comment]
> Hello, as we can see in the url you have, linuxserver is expecting /api/oauth/spotify/callback. I think just adding the api prefix should fix the whole thing.

Worked for me.

Docs should probably be updated as they don't seem to mention every endpoint is prefixed with /api

**Comment by Yooooomi** [comment]
Doc is for this repo. I checked their repo and they state it.

**Comment by GossamerSolid** [comment]
> Doc is for this repo. I checked their repo and they state it.

![image](https://user-images.githubusercontent.com/2671787/219361644-3f1d9844-de79-44ae-893a-5916b04476d6.png)

**Comment by Yooooomi** [comment]
Yes, if you use the docker-compose example in this repo, client and server are separated, you can host your server wherever you want, meaning you can have any endpoint. That's why I wrote `corresponding to your server location and adding the suffix`.
In their repo, they bundle it with the client, and expose the api under /api.
<img width="858" alt="image" src="https://user-images.githubusercontent.com/17204739/219362384-8ef45175-5302-43bf-b0e1-3cce1864ed9e.png">

**Comment by rh535** [comment]
I appreciate your help Yooooomi! Adding /api fixed it!

**Comment by garrettmueller** [comment]
Incredible. I will try this when I get home from class. Thank you.
