### ISSUE TITLE
Can't connect client with server

### ISSUE THREAD

**Issue by Satalicious** [Yooooomi/your_spotify#206]
**Describe the bug**
Im running proxmox on my homeserver. I got a ubuntu container that has docker and tailscale running.
Im using tailscale as my VPN. With the IP-Address 100.119.199.111 i access my ubuntu container.

**Expected behavior**

To log in and access the webclient.

**Additional context**

_Redirect URIs_

http://100.119.199.111:8085/oauth/spotify/callback
http://localhost:3000/oauth/spotify/callback
http://100.119.199.111:3000/oauth/spotify/callback 
http://localhost:8085/oauth/spotify/callback
http://192.168.0.5:8085/oauth/spotify/callback
http://192.168.0.5:3000/oauth/spotify/callback

_dockercompose.yml_

version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8085:8085"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://100.119.199.111:8085 # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://100.119.199.111:3000
      SPOTIFY_PUBLIC: #provided right one
      SPOTIFY_SECRET: #provided right one
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://100.119.199.111:8085

_sever logs_

yarn run v1.22.19

$ node ./lib/migrations.js

[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify

[info]  Connected to database !

[info]  Starting migrations

[info]  Migrations successfully ran

Done in 0.54s.

yarn run v1.22.19

$ node lib/bin/www

[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify

[info]  Connected to database !

[info]  Checking database...

[warn]  No user is admin, cannot auto fix database

[info]  Starting loop for 0 users

[info]  Starting loop for 0 users

[info]  Starting loop for 0 users

[info]  Starting loop for 0 users

yarn run v1.22.19

$ node ./lib/migrations.js

[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify

[info]  Connected to database !

[info]  Starting migrations

[info]  Migrations successfully ran

Done in 1.54s.

yarn run v1.22.19

$ node lib/bin/www

[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify

[info]  Connected to database !

[info]  Checking database...

[warn]  No user is admin, cannot auto fix database

[info]  Starting loop for 0 users

[info]  Starting loop for 0 users

[info]  Starting loop for 0 users

[info]  Starting loop for 0 users

[info]  Starting loop for 0 users

[info]  Starting loop for 0 users

_webclient logs_

Setting API Endpoint to 'http://100.119.199.111:8085'

 INFO  Accepting connections at http://0.0.0.0:3000

 HTTP  2/22/2023 11:02:38 AM 100.74.210.80 GET /login

 HTTP  2/22/2023 11:02:38 AM 100.74.210.80 Returned 200 in 17 ms

 HTTP  2/22/2023 11:02:38 AM 100.74.210.80 GET /variables.js

 HTTP  2/22/2023 11:02:38 AM 100.74.210.80 Returned 200 in 2 ms

 HTTP  2/22/2023 11:02:38 AM 100.74.210.80 GET /static/js/main.bf85c65a.js

 HTTP  2/22/2023 11:02:38 AM 100.74.210.80 GET /static/css/main.7a14ab5f.css

 HTTP  2/22/2023 11:02:38 AM 100.74.210.80 Returned 200 in 3 ms

 HTTP  2/22/2023 11:02:38 AM 100.74.210.80 Returned 304 in 10 ms

 HTTP  2/22/2023 11:02:38 AM 100.74.210.80 GET /favicon.ico

 HTTP  2/22/2023 11:02:38 AM 100.74.210.80 Returned 200 in 3 ms

 HTTP  2/22/2023 11:02:38 AM 100.74.210.80 GET /logo192.png

 HTTP  2/22/2023 11:02:38 AM 100.74.210.80 Returned 200 in 3 ms

 HTTP  2/22/2023 11:02:40 AM 100.74.210.80 GET /

 HTTP  2/22/2023 11:02:40 AM 100.74.210.80 Returned 200 in 2 ms

 HTTP  2/22/2023 11:02:40 AM 100.74.210.80 GET /variables.js

 HTTP  2/22/2023 11:02:40 AM 100.74.210.80 Returned 304 in 1 ms

 HTTP  2/22/2023 11:02:40 AM 100.74.210.80 GET /static/js/main.bf85c65a.js

 HTTP  2/22/2023 11:02:40 AM 100.74.210.80 Returned 304 in 2 ms

 HTTP  2/22/2023 11:02:40 AM 100.74.210.80 GET /static/css/main.7a14ab5f.css

 HTTP  2/22/2023 11:02:40 AM 100.74.210.80 Returned 304 in 1 ms

 HTTP  2/22/2023 11:02:40 AM 100.74.210.80 GET /favicon.ico

 HTTP  2/22/2023 11:02:40 AM 100.74.210.80 Returned 304 in 1 ms

 HTTP  2/22/2023 11:10:04 AM 100.74.210.80 GET /login

 HTTP  2/22/2023 11:10:04 AM 100.74.210.80 Returned 200 in 1 ms

 HTTP  2/22/2023 11:10:04 AM 100.74.210.80 GET /variables.js

 HTTP  2/22/2023 11:10:04 AM 100.74.210.80 Returned 200 in 1 ms

 HTTP  2/22/2023 11:10:04 AM 100.74.210.80 GET /static/js/main.bf85c65a.js

 HTTP  2/22/2023 11:10:04 AM 100.74.210.80 Returned 304 in 1 ms

 HTTP  2/22/2023 11:10:04 AM 100.74.210.80 GET /static/css/main.7a14ab5f.css

 HTTP  2/22/2023 11:10:04 AM 100.74.210.80 Returned 200 in 1 ms

 HTTP  2/22/2023 11:10:04 AM 100.74.210.80 GET /favicon.ico

 HTTP  2/22/2023 11:10:04 AM 100.74.210.80 Returned 200 in 2 ms

 HTTP  2/22/2023 11:10:05 AM 100.74.210.80 GET /logo192.png

 HTTP  2/22/2023 11:10:05 AM 100.74.210.80 Returned 200 in 2 ms

Setting API Endpoint to 'http://100.119.199.111:8085'

 INFO  Accepting connections at http://0.0.0.0:3000

 HTTP  2/22/2023 11:14:11 AM 100.74.210.80 GET /

 HTTP  2/22/2023 11:14:11 AM 100.74.210.80 Returned 200 in 101 ms

 HTTP  2/22/2023 11:14:11 AM 100.74.210.80 GET /variables.js

 HTTP  2/22/2023 11:14:11 AM 100.74.210.80 GET /static/js/main.bf85c65a.js

 HTTP  2/22/2023 11:14:11 AM 100.74.210.80 GET /static/css/main.7a14ab5f.css

 HTTP  2/22/2023 11:14:11 AM 100.74.210.80 Returned 200 in 2 ms

 HTTP  2/22/2023 11:14:11 AM 100.74.210.80 Returned 200 in 10 ms

 HTTP  2/22/2023 11:14:11 AM 100.74.210.80 Returned 304 in 13 ms

 HTTP  2/22/2023 11:14:12 AM 100.74.210.80 GET /logo192.png

 HTTP  2/22/2023 11:14:12 AM 100.74.210.80 GET /favicon.ico

 HTTP  2/22/2023 11:14:12 AM 100.74.210.80 Returned 200 in 4 ms

 HTTP  2/22/2023 11:14:12 AM 100.74.210.80 Returned 200 in 2 ms

 HTTP  2/22/2023 11:14:12 AM 100.74.210.80 GET /favicon.ico

 HTTP  2/22/2023 11:14:12 AM 100.74.210.80 Returned 304 in 1 ms

 HTTP  2/22/2023 11:14:37 AM 100.74.210.80 GET /login

 HTTP  2/22/2023 11:14:37 AM 100.74.210.80 Returned 200 in 2 ms

 HTTP  2/22/2023 11:14:37 AM 100.74.210.80 GET /variables.js

 HTTP  2/22/2023 11:14:37 AM 100.74.210.80 Returned 304 in 2 ms

 HTTP  2/22/2023 11:14:37 AM 100.74.210.80 GET /static/js/main.bf85c65a.js

 HTTP  2/22/2023 11:14:37 AM 100.74.210.80 Returned 304 in 1 ms

 HTTP  2/22/2023 11:14:37 AM 100.74.210.80 GET /static/css/main.7a14ab5f.css

 HTTP  2/22/2023 11:14:37 AM 100.74.210.80 Returned 200 in 1 ms

 HTTP  2/22/2023 11:14:37 AM 100.74.210.80 GET /favicon.ico

 HTTP  2/22/2023 11:14:37 AM 100.74.210.80 Returned 200 in 1 ms

 HTTP  2/22/2023 11:14:37 AM 100.74.210.80 GET /favicon.ico

 HTTP  2/22/2023 11:14:37 AM 100.74.210.80 Returned 304 in 1 ms

 HTTP  2/22/2023 11:15:03 AM 100.74.210.80 GET /login

 HTTP  2/22/2023 11:15:03 AM 100.74.210.80 Returned 304 in 2 ms

 HTTP  2/22/2023 11:15:03 AM 100.74.210.80 GET /variables.js

 HTTP  2/22/2023 11:15:03 AM 100.74.210.80 Returned 304 in 1 ms

 HTTP  2/22/2023 11:15:03 AM 100.74.210.80 GET /static/js/main.bf85c65a.js

 HTTP  2/22/2023 11:15:03 AM 100.74.210.80 GET /static/css/main.7a14ab5f.css

 HTTP  2/22/2023 11:15:03 AM 100.74.210.80 Returned 304 in 2 ms

 HTTP  2/22/2023 11:15:03 AM 100.74.210.80 Returned 304 in 2 ms

 HTTP  2/22/2023 11:15:03 AM 100.74.210.80 GET /favicon.ico

 HTTP  2/22/2023 11:15:03 AM 100.74.210.80 Returned 304 in 1 ms

**Screenshots**

![problem](https://user-images.githubusercontent.com/91656114/220606973-c3dd9f94-f73f-4b97-840c-b3e65a7f168f.png)
If i press on 'Login' , I'm getting redirected to http://100.119.199.111:8085/oauth/spotify which leads no 'Unable to connect, Firefox can't establish connection'.

I think the solution might be somewhere in the compose file, i've already tried several IP's etc as you can see in the Redirect URIs.
Also, maybe the developer.spotify.com/dashboard might only have access to localhost per default and thats why i dont get a connection?

I also can't access http://100.119.199.111:8085. Accessing Port 3000 leads to the screenshot.

Thanks for help!

**Comment by Yooooomi** [comment]
Hello, can you try putting 8085:8080 for the ports of the server service? The server listens on the port 8080 in the container.

**Comment by Satalicious** [comment]
> Hello, can you try putting 8085:8080 for the ports of the server service? The server listens on the port 8080 in the container.

Thank you very much, this fixed it!
