### ISSUE TITLE
Adding a second user error

### ISSUE THREAD

**Issue by ScrimGit** [Yooooomi/your_spotify#207]
When a second user tries to login it adds the user to the spotify api but when redirecting to the your_spotify instance it goes right back to the login with spotify page in the log i get this message:
```
    },

    data: 'User not registered in the Developer Dashboard'

  }
```
How do i add them to the page?

**Comment by Yooooomi** [comment]
Hello!
Please follow the 5th point of creating the Spotify application.

**Comment by ScrimGit** [comment]
Thanks Yoooomi that worked!
