### ISSUE TITLE
[Feature Request] Build and publish docker images with proper tags

### ISSUE THREAD

**Issue by Byh0ki** [Yooooomi/your_spotify#210]
**Describe the issue**

Currently, docker images are only available with the "latest" tag, this can create unforseen issues during basic maintenance operation and it doesn't allow for fine version control.

**Expected behavior**

All docker images should be tagged using the app version

**Comment by Yooooomi** [comment]
Hey, I see you're working the workflows of the repository. Thanks a lot. However, it would be great to have the tag taken from the package.json files. It would make more sense to have the tag reflecting the version of the app.

Thanks again for your work

**Comment by Byh0ki** [comment]
Hello,

IMO, ensuring that a given version is unique (and thus not rebuilding/overriding an existing tag) is easier using git tags than using the package.json file.

Quick question btw, do you plan to have matching version on the client and the server app at all point? If not, maybe a repo split would be interesting as it might resolve the issue where a tag is not matching both of the package.json versions

**Comment by Yooooomi** [comment]
I feel like semver is easier to understand than SHAs. Yes, client and server versions will always match.

**Comment by Byh0ki** [comment]
I'll open the PR so we can talk about it directly
