### ISSUE TITLE
Language clarity

### ISSUE THREAD

**Issue by flightcode** [Yooooomi/your_spotify#212]
I just want to say first, this project is amazing and I really appreciate the effort put in and detail this provides.

I've noticed some issues where the language/wording used aren't that clear or are a bit confusing.

Would you be happy/welcome for me to create a PR with general wording/clarity improvements?

**Comment by Yooooomi** [comment]
Hello. I'm not a native speaker so I can understand things are sometimes unclear. Would be happy to see what you would improve yes. Thanks a lot
