### ISSUE TITLE
question: does the users of this require premium? I have premium but would like to invite my friend to use the server. do they need it?

### ISSUE THREAD

**Issue by acreiko** [Yooooomi/your_spotify#213]

**Comment by Yooooomi** [comment]
Hello, I think they don't need it. They only need it to play songs from the interface. Be sure to add them to the Spotify dashboard, as stated in the 5th point in the Creating the Spotify application part of the readme.

**Comment by acreiko** [comment]
Ah! Thank you, I must've missed that bit.
