### ISSUE TITLE
cannot interract with buttons

### ISSUE THREAD

**Issue by tikifarm** [Yooooomi/your_spotify#215]
i followed everything that was done in the how to setup readme file; 
my setup works flawlessly in local (exept that i have to click the login button every time i open a new page)
but when i opened it online using reverse DNS, i have a page witout any stats or buttons 
![image](https://user-images.githubusercontent.com/42776726/226100301-2841b3c6-811e-4ba0-90f5-def8e6bfe69a.png)
i tried following what was done on privious bug repport, but it never solved all my problemes,
from the server and web logs, my system is working perfectly, but its never loading.
browser not showing any 404 errors anymore, not getting the "cannot interract with server issue" either

FYI : i used docker compose on unraid server + my reverse DNS is Nginx with GUI and i use cloudflaire
web logs : 

>  HTTP  3/18/2023 10:31:34 AM 172.25.0.1 GET /api/version?token=
>  HTTP  3/18/2023 10:31:34 AM 172.25.0.1 GET /api/me?token=
>  HTTP  3/18/2023 10:31:34 AM 172.25.0.1 Returned 200 in 5 ms
>  HTTP  3/18/2023 10:31:34 AM 172.25.0.1 Returned 200 in 5 ms
>  HTTP  3/18/2023 10:31:34 AM 172.25.0.1 GET /favicon.ico
>  HTTP  3/18/2023 10:31:34 AM 172.25.0.1 GET /api/global/preferences?token=
>  HTTP  3/18/2023 10:31:34 AM 172.25.0.1 Returned 200 in 3 ms
>  HTTP  3/18/2023 10:31:34 AM 172.25.0.1 Returned 200 in 2 ms
>  HTTP  3/18/2023 10:31:35 AM 172.25.0.1 GET /manifest.json
>  HTTP  3/18/2023 10:31:35 AM 172.25.0.1 Returned 200 in 2 ms
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 GET /api/oauth/spotify
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 Returned 200 in 1 ms
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 GET /variables.js
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 GET /static/css/main.7a14ab5f.css
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 Returned 200 in 1 ms
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 Returned 200 in 2 ms
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 GET /static/js/main.bf85c65a.js
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 Returned 200 in 1 ms
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 GET /api/version?token=
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 Returned 200 in 1 ms
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 GET /api/me?token=
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 Returned 200 in 1 ms
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 GET /api/global/preferences?token=
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 Returned 200 in 1 ms
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 GET /manifest.json
>  HTTP  3/18/2023 10:31:55 AM 172.25.0.1 Returned 200 in 1 ms

server logs

> Setting CORS to 'all' is not needed anymore, omitting it is the new way of authorizing every origin.
> yarn run v1.22.19
> $ node ./lib/migrations.js
> [info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
> [info]  Connected to database !
> [info]  Starting migrations
> [info]  Migrations successfully ran
> Done in 1.59s.
> yarn run v1.22.19
> $ node lib/bin/www
> [info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
> [info]  Connected to database !
> [info]  Checking database...
> [info]  Starting loop for 1 users
> [info]  Refreshing songs for Sha
> [info]  User has no new music
> [info]  Starting loop for 1 users
> [info]  Refreshing songs for Sha
> [info]  User has no new music
> [info]  Starting loop for 1 users
> [info]  Refreshing songs for Sha
> [info]  User has no new music
> [info]  Starting loop for 1 users
> [info]  Refreshing songs for Sha
> [info]  User has no new music
> [info]  Starting loop for 1 users
> [info]  Refreshing songs for Sha
> [info]  User has no new music

i never really use github, hope i did it right, and thanks for all your work <3

edit : forgot the config files

> 
> version: "3"
> 
> services:
>   server:
>     image: yooooomi/your_spotify_server
>     restart: always
>     ports:
>       - "8080:8080"
>     links:
>       - mongo
>     depends_on:
>       - mongo
>     environment:
>      API_ENDPOINT: https://domain.fr/api # This MUST be included as a valid URL in the spotify dashboard (see below)
>      CLIENT_ENDPOINT: https://domain.fr
>      SPOTIFY_PUBLIC: ___
>      SPOTIFY_SECRET: ___
>      CORS: all
>   mongo:
>     container_name: mongo
>     image: mongo:4.4.8
>     volumes:
>       - /mnt/user/appdata/spotify:/data/db
> 
>   web:
>     image: yooooomi/your_spotify_client
>     restart: always
>     ports:
>       - "3000:3000"
>     environment:
>       API_ENDPOINT: https://domain.fr/api

edit 2, reverse DNS settings
![image](https://user-images.githubusercontent.com/42776726/226100889-b2409ba6-c0fb-4f46-9134-f6773795cc64.png)
![image](https://user-images.githubusercontent.com/42776726/226100900-c30b8004-67d3-4abd-a51e-02b750578fb9.png)

**Comment by Yooooomi** [comment]
Hello, if you have to relog every time this surely means the cookies are not stored right. You should maybe have a look into this.

**Comment by tikifarm** [comment]
thanks for the tip!
but im kind of a newbee about all this, changed some cookie setting on chrome to see,
i tried logging in with different browsers / private browsing and it seems the system is requesting me to login but not bringing me to a login page, just to the empty page when i presse the login button
so the redirection dosen't seem to be working correctly

**Comment by tikifarm** [comment]
welp, i have no idea why and how, i just redid the same thing i did last week and the week prior.... and its now working...
looks like 3dr time is the charm ?
might have been cookies,
thanks for the help :)
