### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by esmoyer** [Yooooomi/your_spotify#219]
I have to say this is a really cool tool! I'm curious if there is a way to change the way the date is formatted. Not really a big deal, just wasn't sure if I happened to overlook something. Thanks!

**Comment by Yooooomi** [comment]
Hello! Date format is fixed since no translation system in on yet. I'm sorry if you don't feel at ease with this format. I assume you're looking for the US format. 
Might have a look when I'm really determined since translation at this stage starts to be a big deal.

**Comment by esmoyer** [comment]
No worries, just wanted to be sure I wasn't overlooking something. I'm actually kind of weird and like YYYY/MM/DD ha! Thanks!
