### ISSUE TITLE
Error: The initialization failed, maybe your files are wrongly formatted

### ISSUE THREAD

**Issue by dh2-io** [Yooooomi/your_spotify#224]
## **Describe the bug**
After going to the settings and choosing the option to import data from the privacy data and selecting the files that start with `endsong`, it loads like 4 minits and that i shows an error, that the files are wrongly formated and can not be imported 

## **Expected behavior**
Uhm , so I expected it to load a bit and then start the import, like it did with the Account Data/ the Basic streaming history.
![Normal import works just fine](https://i.dh2.io/paRo3/XENUrALI39.png/raw)

## **Additional context**
###Here some links and images 
- Error message in Settings: 
![](https://i.dh2.io/paRo3/diDutiRE92.png/raw)
- Server Logs: 
[https://paste.dh2.io/inucizemas.yaml](https://paste.dh2.io/inucizemas.yaml)
- Browser Logs (Header): 
![](https://i.dh2.io/paRo3/CuZEPILu53.png/raw)
- Browser Logs (Response):
![](https://i.dh2.io/paRo3/popemOwa63.png/raw)

I can send you the files via discord if you want or i´ll send them here as links.

## **Shared link**

https://spotistats.dh2.io/?gname=Last+day&token=bd15cedb-7fb7-4525-8eac-0fee0f1664ba

**Comment by Yooooomi** [comment]
Hello, yes it could be great to have them to investigate, feel free to add me on discord: Marvin the Martian#8336. Many thanks

**Comment by dh2-io** [comment]
👍 My username on Discord is Dust!n#0666

**Comment by grxphxnxx** [comment]
i get the same error when i try to import my endsong_x.json files, can you please add me on discord and i can send them to you: Graphxne#0632

i really love the idea behind your project and it would be so nice if i could import my entire listening history of 7 years. thank you for your effort :)

**Comment by dh2-io** [comment]
> i get the same error when i try to import my endsong_x.json files, can you please add me on discord and i can send them to you: Graphxne#0632
> 
> i really love the idea behind your project and it would be so nice if i could import my entire listening history of 7 years. thank you for your effort :)

The current solution for error is the nightly build,
Just change the docker reales to `yooooomi/your_spotify_server:nightly`.
