### ISSUE TITLE
Problem: The web application can't communicate with the server

### ISSUE THREAD

**Issue by lukuhn** [Yooooomi/your_spotify#226]
Hey sorry for the dumb questions, I am quite new to this things.
I have set my docker compose file to this:

`version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://192.168.178.63:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: https://192.168.178.63:3000
      SPOTIFY_PUBLIC: xxxx
      SPOTIFY_SECRET: xxx
  mongo:
    container_name: mongo
    image: mongo:4.4.8
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://localhost:8080`
In the Spotify developer Account I have set this URIs:
    http://localhost:3000/oauth/spotify/callback
    http://localhost:8080/oauth/spotify/callback
    http://192.168.178.63:8080/spotify/callback
    https://192.168.178.63:8080
    https://192.168.178.63:3000

But when I try to logn in I get this error: The web application can't communicate with the server
I also get the hello! on http://192.168.178.63:8080/

What extra things are also nesseary ?
Do i need ngix or something like this ?
Thanks for your help!

**Comment by Yooooomi** [comment]
Hello! You can use local addresses if you want to access your service from within your home only. Nginx and stuff will appear if you want it to be accessible over the internet.
Your problem seems to be the API_ENDPOINT in your web service. This should be the same as the one in your server. What it is actually doing is when you go to the website, it tries to communicate with a server on the current machine, which is rarely what you want.

**Comment by Yooooomi** [comment]
Your setup is http and not https, try to only use http addresses.

**Comment by renolation** [comment]
hello @Yooooomi  i also have this problem, my ip is 144.24.113.211
here is my settings 
```
 API_ENDPOINT: http://144.24.113.211:8080 
 CLIENT_ENDPOINT: http://144.24.113.211:3000
```
it the same with web container API_ENDPOINT, what is wrong ?
