### ISSUE TITLE
Local installation 

### ISSUE THREAD

**Issue by pachakutiq199999** [Yooooomi/your_spotify#229]
Hello, I am stuck in the server ‘yarn migrate’ part.

How can I input the env variable?

**Comment by Yooooomi** [comment]
Hello, as you would launching a normal command:

`VAR=something yarn migrate`

**Comment by pachakutiq199999** [comment]
Thank you.

I have no knowledge in these area.
I have just installed mongodb, what should I input in the mongodb endpoint?

**Comment by Yooooomi** [comment]
I feel like if you're this new you should learn how to use the docker compose. It'll be faster to setup than having to set up all the stacks.

Otherwise mongodb://localhost:27017 should do the trick

**Comment by Yooooomi** [comment]
You should use local addresses instead of 0.0.0.0 in your compose file.

**Comment by pachakutiq199999** [comment]
how can i make it accessible over the internet?

**Comment by pachakutiq199999** [comment]
Hello, I have successfully installed.
I found issue#112 very useful, maybe you can include that in readme
