### ISSUE TITLE
Caddyv2 reverse proxy redirect issues

### ISSUE THREAD

**Issue by MHunton** [Yooooomi/your_spotify#230]
I'm not sure if I have done something wrong as I'm quite new to caddy and selfhosting in general but when I load the login screen I get an error message saying "cannot connect to server", when I click login it redirects me and says "this page isn't working".
Apologies if this is a simple issue and my own fault. Thanks in advance.

below is my docker compose and caddy v2 settings

version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "888:888"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://spotiserv.mydomain.com/oauth/spotify/callback # This MUST be included as a valid URL in the spotify dashb>      CLIENT_ENDPOINT: https://spotify.mydomain.com
      SPOTIFY_PUBLIC: 
      SPOTIFY_SECRET: 
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - ./your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: https://spotiserv.mydomain.com/oauth/spotify/callback
            
----------      
This is in my caddy file:

spotify.mydomain.com {
        reverse_proxy http://localhost:3000
}

spotiserv.mydomain.com {
        reverse_proxy http://localhost:888
}

**Comment by Yooooomi** [comment]
Hello. You cannot change the inner port of the container. In the server, your ports definition should be 888:8080

**Comment by MHunton** [comment]
> Hello. You cannot change the inner port of the container. In the server, your ports definition should be 888:8080

Thank you so much, I knew it would be something I'd done wrong, I also realised I had my API URL entered wrong but I sorted that myself, it's working perfectly now!
