### ISSUE TITLE
Holes in listening history

### ISSUE THREAD

**Issue by BlipRanger** [Yooooomi/your_spotify#233]
**Describe the bug**

Some songs seem to appear, but many do not. It appears that the Spotify api is not providing matching output to the recently played list I see on my phone or desktop application.

**Expected behavior**

Recently played songs would be consistent between Spotify's output and what the api is providing. 

**Additional context**

_Docker Compose is default config_

The logs indicate that there is no new music, so perhaps Spotify is just not providing all of my recent history. Do you know why that might be?  All of the songs in the screenshot below were played within the last 24 hours. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1860540/232671551-414ba536-480c-46c8-98e9-7cb8054c8bec.png)

![image](https://user-images.githubusercontent.com/1860540/232671495-9933dc2b-30a2-4939-99ec-264d02a1e689.png)

**Shared link**

**Comment by Yooooomi** [comment]
Hello! This is weird. If it logs that there are no new music this means Spotify didn't send the latest songs. 
Are you listening in private mode? 
If not, then you should test with a fresh instance if the problem still persists.

**Comment by BlipRanger** [comment]
> Hello! This is weird. If it logs that there are no new music this means Spotify didn't send the latest songs. 
> Are you listening in private mode? 
> If not, then you should test with a fresh instance if the problem still persists.

I've been doing some reading on the Spotify dev forum and I think the issue is actually that the contents that the api reports for recently played are only songs that are fully listened to, not partials. The recently played on the Spotify client seems to report both partials and fully played songs.

**Comment by Yooooomi** [comment]
I feel like there's nothing more I can do about this. Hope the actual system is great only recording fully listened songs, what do you think?

**Comment by BlipRanger** [comment]
Yeah, it's good, we can close this issue; it's really more Spotify's problem.
