### ISSUE TITLE
Refresh Interval

### ISSUE THREAD

**Issue by rondDev** [Yooooomi/your_spotify#238]
Not really a bug or improvement, I was just wondering how often the stats update? And if this is set by y_r or spotify, therefore if it can be changed?

**Comment by Yooooomi** [comment]
Hello! The loop refreshing the stats loads all the users and refreshes them continuously spaced by a 2 minutes interval. Once the loop ends, it fetches all the users again and restart the process.
I hope this is the info you're looking for.

**Comment by rondDev** [comment]
Thank you :)
