### ISSUE TITLE
Transferring installation to a new Docker host

### ISSUE THREAD

**Issue by chrisg991** [Yooooomi/your_spotify#24]
Hello,
I would like to transfer my current installation of your_spotify to a new Docker host. For compatibility, I imagine it would be best to deploy an entirely new installation and then copy my existing data across manually - is this sensible? If so, which files will I need to copy from my old installation to my new one to retain all my listening data, please? 

Thank you

**Comment by Yooooomi** [comment]
Hello,
To change the host of my yourspotify, I would simply copy the volume data to my new docker host. Just zip your volume and unzip it on the other host.
Do not hesitate to backup your zip so it's safe.
Feel free to comment this issue if you have any doubts.
Best of luck

**Comment by chrisg991** [comment]
Thank you very much for your prompt reply. I've installed a fresh version on my new host and then copied across the your_spotify_db folder and everything seems to be working ok. Are there any other files/folders that I will need, too?

Thanks again

**Comment by Yooooomi** [comment]
The db is the only thing you need, sorry for the late answer.
Marking this as closed
