### ISSUE TITLE
Help with setup?

### ISSUE THREAD

**Issue by mcrummett** [Yooooomi/your_spotify#240]
Hi

I was hoping i may be able to get some help setting this up.  I have followed both the readme guide and the breadnet guide but still have no success.

I seen to be up and running in that it connects to the database and the webpage under port 3000 opens. However it warns that it can't connect to the server.  I have managed to enter my Spotify login details and then i just get connection refused when it tries to go further.

**Comment by mcrummett** [comment]
I've resolved this now having read an explanation on another issue of exactly what addresses should be where :)

**Comment by Yooooomi** [comment]
Hello, glad you got it working! If you post another issue one day, please post your configuration files too as it's impossible for me to know what's wrong without them.
