### ISSUE TITLE
Feature request - Implement support for podcasts

### ISSUE THREAD

**Issue by jamess60** [Yooooomi/your_spotify#244]
Hi @Yooooomi 

I recently started using Spotify for podcasts too and noticed YSS does not track this. 

Assuming its trivial to implement, would it be possible to also track podcast time, then maybe display music time listened, podcast time listened and total minutes listened?

**Comment by Yooooomi** [comment]
Hello. I don't listen to podcasts so I never noticed. I do not provide any parameter that excludes the podcasts from the request. I'm assuming either there is another endpoint to call or this is juste not possible.
I'll have a look at their api again and keep you informed.
This is not so trivial in my opinion.

**Comment by jamess60** [comment]
No worries, thanks for looking into it :) 
If it isnt a super quick fix, don't spend time on it just for me. We should see if others are interested too :)

Cheers

**Comment by Yooooomi** [comment]
It seems that it's not supported yet. It is the third line of [this](https://developer.spotify.com/documentation/web-api/reference/get-recently-played) page.

**Comment by jamess60** [comment]
No problem - thanks for looking!

**Comment by JamesDAdams** [comment]
Hi,  the api doesn't return the podcast but if we request privacy data we receive the podcast history, that would be great to add this support no ?
