### ISSUE TITLE
cant connect to db

### ISSUE THREAD

**Issue by skypeks** [Yooooomi/your_spotify#251]
hey im running unraid 6.11 with the docker compose plugin, if i try to run your_spotify i get this error

your_spotify-server-1  | [info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
your_spotify-server-1  | /app/node_modules/mongoose/lib/connection.js:755
your_spotify-server-1  |     err = new ServerSelectionError();
your_spotify-server-1  |           ^
your_spotify-server-1  | 
your_spotify-server-1  | MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
your_spotify-server-1  |     at _handleConnectionErrors (/app/node_modules/mongoose/lib/connection.js:755:11)
your_spotify-server-1  |     at NativeConnection.openUri (/app/node_modules/mongoose/lib/connection.js:730:11) {
your_spotify-server-1  |   reason: TopologyDescription {
your_spotify-server-1  |     type: 'Unknown',
your_spotify-server-1  |     servers: Map(1) {
your_spotify-server-1  |       'mongo:27017' => ServerDescription {
your_spotify-server-1  |         address: 'mongo:27017',
your_spotify-server-1  |         type: 'Unknown',
your_spotify-server-1  |         hosts: [],
your_spotify-server-1  |         passives: [],
your_spotify-server-1  |         arbiters: [],
your_spotify-server-1  |         tags: {},
your_spotify-server-1  |         minWireVersion: 0,
your_spotify-server-1  |         maxWireVersion: 0,
your_spotify-server-1  |         roundTripTime: -1,
your_spotify-server-1  |         lastUpdateTime: 119559292,
your_spotify-server-1  |         lastWriteDate: 0,
your_spotify-server-1  |         error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
your_spotify-server-1  |             at connectionFailureError (/app/node_modules/mongodb/lib/cmap/connect.js:383:20)
your_spotify-server-1  |             at Socket.<anonymous> (/app/node_modules/mongodb/lib/cmap/connect.js:307:22)
your_spotify-server-1  |             at Object.onceWrapper (node:events:628:26)
your_spotify-server-1  |             at Socket.emit (node:events:513:28)
your_spotify-server-1  |             at emitErrorNT (node:internal/streams/destroy:157:8)
your_spotify-server-1  |             at emitErrorCloseNT (node:internal/streams/destroy:122:3)
your_spotify-server-1  |             at processTicksAndRejections (node:internal/process/task_queues:83:21) {
your_spotify-server-1  |           cause: Error: getaddrinfo ENOTFOUND mongo
your_spotify-server-1  |               at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
your_spotify-server-1  |             errno: -3008,
your_spotify-server-1  |             code: 'ENOTFOUND',
your_spotify-server-1  |             syscall: 'getaddrinfo',
your_spotify-server-1  |             hostname: 'mongo'
your_spotify-server-1  |           },
your_spotify-server-1  |           [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
your_spotify-server-1  |         },
your_spotify-server-1  |         topologyVersion: null,
your_spotify-server-1  |         setName: null,
your_spotify-server-1  |         setVersion: null,
your_spotify-server-1  |         electionId: null,
your_spotify-server-1  |         logicalSessionTimeoutMinutes: null,
your_spotify-server-1  |         primary: null,
your_spotify-server-1  |         me: null,
your_spotify-server-1  |         '$clusterTime': null
your_spotify-server-1  |       }
your_spotify-server-1  |     },
your_spotify-server-1  |     stale: false,
your_spotify-server-1  |     compatible: true,
your_spotify-server-1  |     heartbeatFrequencyMS: 10000,
your_spotify-server-1  |     localThresholdMS: 15,
your_spotify-server-1  |     setName: null,
your_spotify-server-1  |     maxElectionId: null,
your_spotify-server-1  |     maxSetVersion: null,
your_spotify-server-1  |     commonWireVersion: 0,
your_spotify-server-1  |     logicalSessionTimeoutMinutes: null
your_spotify-server-1  |   },
your_spotify-server-1  |   code: undefined
your_spotify-server-1  | }
your_spotify-server-1  | error Command failed with exit code 1.
your_spotify-server-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jivandabeast** [comment]
Looks like it can't resolve the address, I put the actual IP address of my server the mongo port (`192.168.x.xxx:27017/your_spotify`) instead of the container name (`mongo:27017/your_spotify`)
