### ISSUE TITLE
[Feature Request] Add a "Year to Date" or "This year" option when sorting through date ranges.

### ISSUE THREAD

**Issue by dlmservers** [Yooooomi/your_spotify#253]
Hello!

First I wanna say I appreciate the app you've made. It's been great!

I was wondering if you could add a "Year to Date" or "This year" option when sorting through date ranges. I'm constantly having to do it manually by selecting Jan 1st then the current date.

Thanks!

**Comment by Yooooomi** [comment]
Fixed in latest release :)
