### ISSUE TITLE
Extended streaming history import - new format?

### ISSUE THREAD

**Issue by filcuk** [Yooooomi/your_spotify#264]
**Describe the bug**
Cannot import history due to what I assume is a new format of .json files.

**Additional context**
The files look like below, i.e. no `endsongx.json`, which is what I believe the app expects.
I'm happy to provide a sample, but would prefer to do so privately to the dev(s).

**Screenshots**
![image](https://github.com/Yooooomi/your_spotify/assets/1339532/859f73a1-c1fe-4fef-94eb-7475cfdf4669)

**Shared link**
I don't think it's relevant in this case, but let me know if there's some other way I can help.

As a sidenote, great app! Love it, and it's great knowing I have my data stored where I can see it.

**Comment by filcuk** [comment]
Here's an example of my `Streaming_History_Audio_2014-2018_0.json`:
```
[
    {
        "ts": "2014-08-02T20:35:55Z",
        "username": "g52273418860",
        "platform": "WebPlayer (websocket RFC6455)",
        "ms_played": 225409,
        "conn_country": "GB",
        "ip_addr_decrypted": "2.24.14.42",
        "user_agent_decrypted": "Mozilla%2f5.0%20(Windows%20NT%206.3%3b%20Win64%3b%20x64)%20AppleWebKit%2f537.36%20(KHTML,%20like%20Gecko)%20Chrome%2f37.0.2062.58%20Safari%2f537.36",
        "master_metadata_track_name": "Truth (Helios Remix)",
        "master_metadata_album_artist_name": "Balmorhea",
        "master_metadata_album_album_name": "All Is Wild, All Is Silent Remixes",
        "spotify_track_uri": "spotify:track:4lwGyv3tbahmN1Z25wdCxa",
        "episode_name": null,
        "episode_show_name": null,
        "spotify_episode_uri": null,
        "reason_start": "playbtn",
        "reason_end": "unknown",
        "shuffle": false,
        "skipped": false,
        "offline": false,
        "offline_timestamp": 0,
        "incognito_mode": false
    }
]
```

**Comment by filcuk** [comment]
I should add that in the console, I get `ERR_BAD_REQUEST`:
![image](https://github.com/Yooooomi/your_spotify/assets/1339532/22607ee3-03c1-4e1c-91b6-498d4fe7a38d)

And Docker logs seem to have no sign of an error.

I have run regular account imports successfully:
![image](https://github.com/Yooooomi/your_spotify/assets/1339532/5eefa9fa-28d0-4508-bf82-99dbf0502dd1)

**Comment by dlmservers** [comment]
Also having same issue

**Comment by Yooooomi** [comment]
Hello! The name of the file should have no impact, just a warning. Are you running behind a reverse proxy / cloudflare?

**Comment by filcuk** [comment]
I am behind Traefik 2 and Cloudflare indeed.
I've restarted my instance as local and the import seems to be working now:
![image](https://github.com/Yooooomi/your_spotify/assets/1339532/d34c051d-8e85-432a-b9c3-e9335ad05be5)

I'm going to close the issue.
Could you please give me pointes as to what I should be looking at to fix this @Yooooomi?
@dlmservers I'll let you know if I figure it out.

**Comment by dlmservers** [comment]
> I am behind Traefik 2 and Cloudflare indeed. I've restarted my instance as local and the import seems to be working now: ![image](https://user-images.githubusercontent.com/1339532/255686911-d34c051d-8e85-432a-b9c3-e9335ad05be5.png)
> 
> I'm going to close the issue. Could you please give me pointes as to what I should be looking at to fix this @Yooooomi? @dlmservers I'll let you know if I figure it out.

Updated my server to the latest release and rebooted the containers. Seems okay now, currently in the process of importing

**Comment by filcuk** [comment]
For anyone potentially coming across this with a similar setup...
Ensure that your CORS headers are applied **before** any middlewares that may otherwise overwrite it, i.e.:
```yaml
- "traefik.http.routers.yourspotifyapi-rtr.middlewares=yourspotifyapi-cors@docker,chain-no-auth@file"
```

**Comment by Supbro112** [comment]
I have an issue with importing too, and the format does seem wrong too, but I managed one import but then now it constantly says there is already an import running on the account (??)

**Comment by Yooooomi** [comment]
@Supbro112 can you please, if you don't mind, send me the files you're trying to import on discord @yooooomi_?
