### ISSUE TITLE
Settings Icon changes color on period selection

### ISSUE THREAD

**Issue by CrowMash** [Yooooomi/your_spotify#268]
**Describe the bug**

When you select a period after clicking on the cog icon and the APPLY button, the icon is set in black and is now invisible.

**Expected behavior**

The icon should remain in white.

**Additional context**

I don't know why, but the style in the svg tag is changed with : style="color: rgb(0, 0, 0);"

**Screenshots**

![image](https://github.com/Yooooomi/your_spotify/assets/9526631/c065fd9a-ab93-4177-8d9f-fe408c44c4fc)
![image](https://github.com/Yooooomi/your_spotify/assets/9526631/e3d10f42-cbf2-4119-8fe5-2039d6259b9d)
![image](https://github.com/Yooooomi/your_spotify/assets/9526631/5dff2864-c647-43c5-a5c3-cd116c79c206)

**Comment by Yooooomi** [comment]
Fixed in 1.7.1
