### ISSUE TITLE
Entire domain marked as dangerous

### ISSUE THREAD

**Issue by MHunton** [Yooooomi/your_spotify#271]
My entire domain has been marked as dangerous by google because of the your_spotify application. 
Deceptive pages
Description
These pages attempt to trick users into doing something dangerous, such as installing unwanted software or revealing personal information.
Sample URLs
https://spotify.matterotwo.co.uk/
https://spotify.matterotwo.co.uk/login

This is what the google search console tells me. What is the fix so that my domain is not marked as dangerous?

**Comment by ikaruswill** [comment]
Dropping by and saw this issue, I think you should probably raise [a review request to google](https://developers.google.com/search/docs/monitor-debug/security/social-engineering). Several /r/selfhosted folks have had this problem in the past, you can also look towards that subreddit for what they did.

**Comment by ikaruswill** [comment]
Also, wanted to add that your experience pretty common in self-hosting since some services like `your_spotify` appear to machines as deceptive mimicry of the Spotify frontend. Your subdomain of `spotify` probably also contributes to its "deceptiveness" score.

**Comment by CPanter99** [comment]
any solution other than send a report everytime it gets marked?

**Comment by Pomdre** [comment]
I tested if you have the subdomain test.test.com its fine but when changing it to spotify.test.com its blocking it.

**Comment by Yooooomi** [comment]
Last release should warn you if you're domain contains Spotify in it
