### ISSUE TITLE
Can't import history due to format change

### ISSUE THREAD

**Issue by Ja90n** [Yooooomi/your_spotify#273]
**Describe the bug**

I can't import my listening history because of a file format change.

**Expected behavior**

You need to import a endsong.json file but because of recent changes the format of the .json file changed. these files are now called "Streaming_History_Audio_2016-2021_0.json" for example

**Screenshots**

![image](https://github.com/Yooooomi/your_spotify/assets/81578391/4caa1ad1-1745-49d6-bbfa-1b6ddec8f4f2)

**Shared link**

dm me for this, would not like to leak my ip haha

**Comment by pl4nty** [comment]
Dupe of #264, just ignore the warning and import it

**Comment by Ja90n** [comment]
oh haha. sorry for the dupe. for some reason it works now while it didn't yesterday. thank you and sorry i wasted your time

**Comment by pl4nty** [comment]
all good lol, I'm not a maintainer. just had the same issue today and found the fix in that thread

**Comment by Ja90n** [comment]
ahh okay, thank you 😁
