### ISSUE TITLE
Stay logged in

### ISSUE THREAD

**Issue by dng-nguyn** [Yooooomi/your_spotify#277]
I have noticed that everytime I load the site, I have to log in again via the login page. Is there a way to stay logged in for a long period of time by using cookies and such?

**Comment by Yooooomi** [comment]
Hello! I think the cookie lasts for 1 hour. I could make this customizable.

**Comment by dng-nguyn** [comment]
Yes! I think customizing the login session would be a good addition. Currently, I have to login pretty much every time I want to see my dashboard, which is a little annoying to say the least.

**Comment by Yooooomi** [comment]
It is now possible in 1.7.1 using COOKIE_VALIDITY_MS. Explanation is in the readme.
