### ISSUE TITLE
Can't import data, wrongly formatted: Streaming_History_Audio

### ISSUE THREAD

**Issue by EricFROL** [Yooooomi/your_spotify#284]
I can't upload my extended streaming history data. I get error. I think its because its wrongly formatted.
I have seen that @Yooooomi fixes it by modifying the json files.

Thank you in advance.

**Comment by Yooooomi** [comment]
Hello. Can you please post logs of your services and logs of the browser when doing the request? Also if you could also paste an entry of your json files it would be great too. 
Thanks a lot

**Comment by EricFROL** [comment]
The server log is huge when error occurs. Here is an example:
```
undefined | 0=a 1=r 2=t 3=i 4=s 5=t 6=N 7=a 8=m 9=e 
  ],
  "message": "Required"
 },
 {
  "code": "invalid_type",
  "expected": "string",
  "received": "undefined",
  "path": [
   912,
```
This is the start of the json:
`[{"ts":"2019-11-09T16:34:50Z","username":"xxxx","platform":"xxxx(xxx)","ms_played":23614,"conn_country":"xx","ip_addr_decrypted":"xxxx","user_agent_decrypted":"unknown","master_metadata_track_name":"Dance Monkey","master_metadata_... (and more)`
