### ISSUE TITLE
Admin tab gone from settings

### ISSUE THREAD

**Issue by Shakmir** [Yooooomi/your_spotify#286]
**Describe the bug**

I was checking the settings page, went to admin tab, I thought I was setting myself as an admin but I think I did the opposite, now the tab is gone and I have no other users that could act as admin.

**Expected behavior**

Not a bug but would be clearer to have a toggle button for setting a user as admin or no.

**Additional context**

Again, not a bug so I don't think logs are necessary. I'm hosting the app in Unraid. How do I make myself admin again?

**Screenshots**

![firefox_230925_121225_Xuu50](https://github.com/Yooooomi/your_spotify/assets/29617158/88b308f7-cb28-4acd-920d-45946c5dec93)

**Comment by Yooooomi** [comment]
As of now, there is no possibility to re admin yourself on your own. However since 1.7.1, you cannot unadmin yourself if you're the only one. My advice would be either to erase your database and just reset everything. Or use the mongo cli to flag yourself as admin again.
