### ISSUE TITLE
is it possible to install this without docker on windows 10?

### ISSUE THREAD

**Issue by ohitstom** [Yooooomi/your_spotify#306]
title

**Comment by ohitstom** [comment]
![image](https://github.com/Yooooomi/your_spotify/assets/22730962/04190f29-446c-4027-b290-b81fe441ef17)
![image](https://github.com/Yooooomi/your_spotify/assets/22730962/1a484911-11cb-42c5-873e-8d7da9d0d190)
![image](https://github.com/Yooooomi/your_spotify/assets/22730962/f82501fb-8460-4e26-924b-da8a84fe6fa3)

**Comment by ohitstom** [comment]
i think this is this issue?
![image](https://github.com/Yooooomi/your_spotify/assets/22730962/1f2610da-3f07-49d9-b526-e196dd260a9b)
why is it not 2999

**Comment by Yooooomi** [comment]
Hello, please provide the right env variables when building the web

**Comment by ohitstom** [comment]
> Hello, please provide the right env variables when building the web

the env vars are provided correctly, the issue i have found is with the js. 
window.API_ENDPOINT = 'http://localhost:2999';
is not being set no matter where i put it, if i reload and put that into console asap everything works perfectly.

**Comment by ohitstom** [comment]
found the issue, sorry, i was putting variables.js in the build dir not the public dir 🤦🏻
