### ISSUE TITLE
Feature Request: Date and Time Localization

### ISSUE THREAD

**Issue by barefootpookie8** [Yooooomi/your_spotify#322]
It would be nice to be able to change the date and time formatting based on localization. 
ex. EN-GB: 04/12/2023 OR EN: 12/04/2023

**Comment by Investigamer** [comment]
I agree please would love this implemented, if nothing else a simple docker supported env would be great for togging date standards :)

**Comment by Yooooomi** [comment]
What source do we want to use to provide localized date?
- Browser language?
- Account setting defaulted to browser language?
I honestly have no clue. Would be interested in what you think :)

**Comment by Yooooomi** [comment]
It's also used backend for playlist names when none is provided, so it would maybe be a great idea to have this in the user.

**Comment by hkamran80** [comment]
> What source do we want to use to provide localized date?

I would use an account setting for that, especially if it defaults to the browser language.

**Comment by Yooooomi** [comment]
Included in last release through #377. Hope you'll like it! Tell me if you thought anything different from that. Closing for now
