### ISSUE TITLE
LOG_LEVEL not obeyed.

### ISSUE THREAD

**Issue by codersaur** [Yooooomi/your_spotify#347]
I'm trying to reduce the logging output. I've set LOG_LEVEL=warn, and this seems to have reduced some of the noise, but I'm still seeing lots of GET access logs which I would like to supress. Mainly http responses from the Spotify API with 304 or 200 response codes (which should not be regarded as warns or errors).

```
GET /spotify/songs_per?start=2024-02-25T14:08:59.769Z&end=2024-02-26T14:08:59.769Z&timeSplit=all 304 31.029 ms - -
GET /spotify/songs_per?start=2024-02-24T14:08:59.769Z&end=2024-02-25T14:08:59.769Z&timeSplit=all 304 28.757 ms - -
GET /spotify/time_per?start=2024-02-24T14:08:59.769Z&end=2024-02-25T14:08:59.769Z&timeSplit=all 304 14.781 ms - -
GET /spotify/top/artists?start=2024-02-25T14:08:59.769Z&end=2024-02-26T14:08:59.769Z&nb=20&offset=0 200 19.202 ms - 6212
```

Expected Behaviour: Setting LOG_LEVEL=warn supresses all non-error/warning messages (including access logs).

**Comment by Yooooomi** [comment]
Fixed in 1.8.0
