### ISSUE TITLE
[Feature Request] Return version without login

### ISSUE THREAD

**Issue by bloedboemmel** [Yooooomi/your_spotify#359]
Just a very small tweak, but it would help a lot monitoring my projects with [Argus](https://github.com/release-argus/Argus)

Would it be possible to return the version, when using the GET /version from the API   https://github.com/Yooooomi/your_spotify/blob/bba31e0debe90ac9fc86dfe45490fa7b1169647d/apps/server/src/routes/index.ts#L194

Or do you consider it a security risk?

**Comment by Yooooomi** [comment]
Do you know any other project that allows fetching the version using GET for your monitoring? How do you do usually to connect these projects to your Argus thing?

**Comment by bloedboemmel** [comment]
Bitwarden gives you the version without a login at admin/home/getinstalledwebversion
and Audiobookshelf sends it in the html without login, you just need to regex it.

I would also help just to put it in the headers of the login html

**Comment by quentinguidee** [comment]
Immich seems to provide this too https://immich.app/docs/api/get-server-version

**Comment by Yooooomi** [comment]
I'll definitely fix this next release then
