### ISSUE TITLE
oath returns 502

### ISSUE THREAD

**Issue by kajvans** [Yooooomi/your_spotify#361]
the oath route for the api returns 502. it does not matter how you try to access it but it always gives an 502.
localhost:8080/oauth/spotify/callback. 
if i look at the docker it gives this error:
```
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
also this:
```
    data: {
      error: 'invalid_request',
      error_description: 'code must be supplied'
    }
```
so something is not being send and that makes the server crash

**Comment by Yooooomi** [comment]
Hello, can you paste your config files on here so I can see clearer in this issue? Also 502 often means something is wrong with your reverse proxy.

**Comment by stephanschorer** [comment]
hello, just wanted to add my solution, cause I experienced the same issue:

I needed to update the mongo db to version 6 but keep the following in mind
> To upgrade an existing MongoDB deployment to 6.0, you must be running a 5.0-series release. To upgrade from a version earlier than the 5.0-series, you must successively upgrade major releases until you have upgraded to 5.0-series.

therefore, edit the mongo db version in your docker-compose first to the next major release in my case mongo:5 (cause I had a 4.4.8 version prior) afterward the yourspotify service worked again, just to be sure I upgraded then to mongo:6

**Comment by kajvans** [comment]
will these keep al the data or will it be removed?

**Comment by stephanschorer** [comment]
the database itself isnt broken just the connection from yourspotify to the db - at least in my case..
So if you keep the upgrading process (one major release at a time) in mind, everything should be there.

You could to a backup just in case

**Comment by kajvans** [comment]
the api is not connecting to the database. with mongo version 5 and also 6

**Comment by stephanschorer** [comment]
oh okay.. yeah I am on x86_64

**Comment by kajvans** [comment]
oke i moved the server to my own pc so on x86_64 but still nothing. if i make the api calls by hand it works fine and even the website says the calls return status 200 and i can see it in the logs but the network creates an missing cors error with missingalloworiginheader while i set both my url correctly:

      CORS: https://spotifyapi.example.com, https://spotify.example.com
      
      when i click each one of the links i get the return you expect

**Comment by stephanschorer** [comment]
try it with out the cors in your docker compose

**Comment by kajvans** [comment]
thanks works now, should have thought of that myself. really thank you

**Comment by kajvans** [comment]
is there a way to fetch everything from the last few days or not? it was down from since 11-03

**Comment by stephanschorer** [comment]
no thats not possible I think you could request all your data, but that could take 30 days...

**Comment by Yooooomi** [comment]
> is there a way to fetch everything from the last few days or not

@kajvans I was looking to implement such a feature, but it's a Spotify limitation, not allowing to request more than 8 hours earlier it seems. Feel free to close the issue if your problem is solved :)

**Comment by kajvans** [comment]
Yeah outside of the fetching of the data from last days problem fixed
