### ISSUE TITLE
Data is not being pulled from Spotify.

### ISSUE THREAD

**Issue by dlmservers** [Yooooomi/your_spotify#369]
**Describe the bug**
Data is not being pulled from Spotify after 2024/03/08
Logs may suggest improper authorization, I've rotated my key with no success. Unsure what the issue is.

**Expected behavior**
The data should be pulled.

**Screenshots**
![image](https://github.com/Yooooomi/your_spotify/assets/138249392/e0448fab-4fe4-4bbd-bbda-4bd5d08c0fe6)
You can see activity drop off in this screenshot. Appears to have happened after I updated to 1.8.1 and 1.9
Rolling back to 1.7.3 or 1.8.0 does not fix the issue.

See attached logs and compose

[docker-compose.txt](https://github.com/Yooooomi/your_spotify/files/14592835/docker-compose.txt)
[spotify-server-1_logs.txt](https://github.com/Yooooomi/your_spotify/files/14592836/spotify-server-1_logs.txt)
[spotify-web-1_logs.txt](https://github.com/Yooooomi/your_spotify/files/14592837/spotify-web-1_logs.txt)

**Comment by Yooooomi** [comment]
You just need to hit the relog button in the settings page. It seems that your refresh token is not available anymore. Also, please do not downgrade the version, as it could lead to undesired behavior and potentially unrecoverable corruption.

**Comment by dlmservers** [comment]
> You just need to hit the relog button in the settings page. It seems that your refresh token is not available anymore. Also, please do not downgrade the version, as it could lead to undesired behavior and potentially unrecoverable corruption.

Gotcha, I had snapshots of the VM it was running on, restored a copy before I upgraded. I don't see any signs of corruption however doing a relog did not help. This problem is for all 3 of the accounts registered on the server.

**Comment by Yooooomi** [comment]
Can you try creating another Spotify application and adding the 3 users to this application and update the tokens accordingly in your compose file?

**Comment by dlmservers** [comment]
That did it, I guess Spotify had an issue with my previous application. 

It appears to have only pulled data back to the 12th, so I'm missing ~3 days (9th-11th). Anyway I can get that data in? I'm sure it's a limitation of the API but honestly not a big deal just curious.

**Comment by Yooooomi** [comment]
That's weird! You could maybe edit the last time is synced in the database for your account to force to request from 3 days ago but I'm not sure it would work. Otherwise ask for your privacy data but not the most simple thing.
Glad creating a new application worked to be honest, otherwise I would be completely lost. Closing a resolved :)
