### ISSUE TITLE
Ability to change user password?

### ISSUE THREAD

**Issue by EricAndrechek** [Yooooomi/your_spotify#38]
I created an account and linked it, but I want to change the password to log in to something different. I know I can make a new account, but then all my existing data is gone. Is there a way to do it another way? I was thinking I could possibly go in and find the file the password is saved in and change it, but I do not know enough to know where to look.

**Comment by Yooooomi** [comment]
There is actually no way to change your password currently except by editing the database by hand. I will try to implement this feature in the next release. Thanks for your feedback

**Comment by Yooooomi** [comment]
The ability to change a password has been implemented in the last release. I'm closing this issue. Feel free to open a new one if you face issues.

**Comment by EricAndrechek** [comment]
Fantastic, just pulled the latest docker image and updated and it works like a charm with no hassle at all, thanks!
