### ISSUE TITLE
Could not play song, no player detected

### ISSUE THREAD

**Issue by GD-Dal** [Yooooomi/your_spotify#388]
According to [this](https://github.com/Yooooomi/your_spotify/issues/231) I should be able to play songs if I have Spotify openend on my (Windows) desktop.
I have that, but I still get the message that no player is detected.
I have tried to open your_spotify in 2 different browsers.
Am I missing something?

Thanks

**Comment by Yooooomi** [comment]
Hello! This is weird. Do you have a premium account?

**Comment by GD-Dal** [comment]
Hi.
Yes I have a premium account

**Comment by Yooooomi** [comment]
Does it output anything backend? Any error? 
Just checked and it works on my end.
Do you have the official desktop Spotify application? Is it up to date? Is it the Microsoft store one?
I honestly have no clue at this point, I'm trying to find something that differs from me.

**Comment by Yooooomi** [comment]
Hello, is this still an issue?

**Comment by GD-Dal** [comment]
Hi.
Just tested it, and now it seems to work just fine :)
Excellent, thank you!
