### ISSUE TITLE
Error when importing account data

### ISSUE THREAD

**Issue by jessenolan1** [Yooooomi/your_spotify#391]
**Describe the bug**

When i requested my Account Data, I received 3 files. One of the files is called `StreamingHistory_podcast_0.json` and breaks the import process. When trying to upload again, i get a prompt saying an import is already in progress. The only way ive found to reset is to restart the containers.

**Expected behavior**

I think that there should be some verbiage added advising to only upload the music json files and also some filename validation would be nice to ensure that the podcast file/s arent being selected

**Additional context**

The reason why its failing is because its missing the artistName and trackName keys. Below is what my file looks like.

```
[
  {
    "endTime" : "2023-09-15 14:04",
    "podcastName" : "Everyday Ethics",
    "episodeName" : "Lying To Grandma",
    "msPlayed" : 1065494
  },
  {
    "endTime" : "2023-09-15 14:13",
    "podcastName" : "Everyday Ethics",
    "episodeName" : "Santa Claus",
    "msPlayed" : 462541
  },
  {
    "endTime" : "2023-09-15 22:50",
    "podcastName" : "Everyday Ethics",
    "episodeName" : "Baby, It's Cold Outside",
    "msPlayed" : 944773
  }
]
```

**Comment by Serpensin** [comment]
Use the extended History files, since those work. I have the same issue, but that fixed it for me.
https://github.com/Yooooomi/your_spotify/issues/329

**Comment by jessenolan1** [comment]
It seems like i still have an issue there
![image](https://github.com/Yooooomi/your_spotify/assets/114173798/b2910ea9-0d14-4ef1-b229-d6c6bf0630a7)

**Comment by Serpensin** [comment]
I maybe recommend then, to simply clear/reset your database, if possible.

**Comment by jessenolan1** [comment]
On the 18th, i started over and redeployed everything. So i did the import of 4/18 that worked and then did the second import the next morning.
