### ISSUE TITLE
Can someone help me, how can i update the docker-compose.yml to the latest version? 

### ISSUE THREAD

**Issue by enough-jainil** [Yooooomi/your_spotify#392]
How can i get the latest version??

**Comment by aseevlx** [comment]
Navigate to the folder where your `docker-compose.yml` file is located and pull latest images:
```
docker compose pull
```
Then restart the containers:
```
docker compose up -d
```

----
If you use a custom filename instead of `docker-compose.yml` or want to run the update from a different location, you can specify the file path:
```
docker compose -f some/custom/dir/filename.yml pull
docker compose -f some/custom/dir/filename.yml up -d
```

**Comment by enough-jainil** [comment]
i just remember docker compose pull cmd 🙂
