### ISSUE TITLE
Web application cant communicate with server, using cloudflare tunnels

### ISSUE THREAD

**Issue by Techsmith404** [Yooooomi/your_spotify#416]
**Describe the bug**

cant login using cloudflare tunnels, works fine using local addresses

**Expected behavior**

login takes me to normal login page and everything works

**Additional context**
my compose.yaml

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: http://spot2.xxx.com # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://spot.xxx.com
      SPOTIFY_PUBLIC: shhhhSecret
      SPOTIFY_SECRET: shhhhSecret
  mongo:
    container_name: mongo
    image: mongo:6
    volumes:
      - /opt/docker/spotify:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://spot2.txxx.com

spot.xxx.com points to localhost:3000
spot2.xxx.com points to localhost:8080

**Screenshots**

![Screenshot 2024-08-08 174639](https://github.com/user-attachments/assets/14779f55-7803-4b06-a7c5-7fa6e0199342)
![Screenshot 2024-08-08 175124](https://github.com/user-attachments/assets/411ad00a-63ef-473f-8bb8-cf1d00641bec)

**Shared link**

**Comment by CEO-Enzo** [comment]
Hello, I have the same problem

**Comment by RagingCactus** [comment]
This is not my project, and I'm not trying to be rude here, but please try to emphasize with the people you are expecting help from. What are we supposed to do here without any detailed information on what is happening? Your description of the behavior is "cant login" with no further details. This is not actionable for me (and likely for most other people as well).

This is a (non-exhaustive) list of what could help:
* What _exactly_ is happening? Are you getting redirected? Are there any error messages?
* You need to provide logs for all containers.
* You need to provide logs from the browser. This includes console output and errors in the network tab of the developer tools.
* It would help if you provided the URL of an affected instance so that others can investigate if the required investigation is beyond your personal ability (which is totally fine, but then we need to be able to get the information ourselves)

Also, please note that this project is not affiliated with Cloudflare Tunnels in any way. Personally, I don't use it, so I don't know about any potential pitfalls. There is a high possibility that the issues are not caused by YourSpotify itself, but by Cloudflare Tunnels or your configuration of them. In this case I would expect more information and effort being put into the issue description before I can motivate myself to put my own effort into it.

I hope you understand where this is coming from and that I'm not trying to pick on you personally. If there is an underlying issue on the YourSpotify side that should be fixed I really want to get to the bottom of it and fix it.

**Comment by Techsmith404** [comment]
> This is not my project, and I'm not trying to be rude here, but please try to emphasize with the people you are expecting help from. What are we supposed to do here without any detailed information on what is happening? Your description of the behavior is "can't log in" with no further details. This is not actionable for me (and likely for most other people as well).

im sorry i thought i provided enough information for you to at least understand what is happening. like ive said everything works fine using local addresses, but when connecting through Cloudflare tunnels (which is where i have most of my self-hosted services routed through) i get to the first page but clicking login just loads for a second and then reloads the page. idk if its redirecting back to the main page or just fails to get through to the second page.  i will set it back up to route through cloudflare and post the logs you requested. the main reason i redacted the address is cause 1 i have it set so only specific people can get through to the page and 2 after posting this i set it back to local addresses so i could still use it at least at home. give me a few tho and i will post all the requested logs and setups. if you have any other questions for me lmk

**Comment by Techsmith404** [comment]
logs from server before clicking login 
![Screenshot 2024-08-09 201511](https://github.com/user-attachments/assets/f67033a4-7440-4a2f-b560-8e9da33582fd)

logs from web before clocking login
![Screenshot 2024-08-09 201524](https://github.com/user-attachments/assets/18ffacfb-b411-462e-bb2a-cf0ade557ac8)

logs from chrome console before clicking login
![Screenshot 2024-08-09 201602](https://github.com/user-attachments/assets/ce925e49-7156-4029-b7b6-71b023943091)

logs from console after
![Screenshot 2024-08-09 201614](https://github.com/user-attachments/assets/893c47a6-8ced-4215-ae94-5e4437e1066b)

logs from server after
![Screenshot 2024-08-09 201635](https://github.com/user-attachments/assets/d15fdbc4-08ec-4525-bf71-3ae076f6c26c)

logs from web after
![Screenshot 2024-08-09 201647](https://github.com/user-attachments/assets/220f0470-206a-45a8-b6a8-3968003db613)


i diddnt think about looking at the chrome console logs, but after looking at them it looks like something to do with cors? or maybe something to do with how cloudflare tunnels turns http into https? im gunna play around with a few things now that i have some leads. if i figure it out ill post my solution. if anyone reading this knows the solution that would be nice too tho

**Comment by Techsmith404** [comment]
yeah so it's definitely an issue with Cloudflare redirecting http into https. is there a way this app can run on https? or does anyone know how to stop cloudflare from doing that?

**Comment by Techsmith404** [comment]
i tried changing the endpoints to https instead of http and updating the spotify app to add those web addresses aswell and im still getting errors about mismatched http/https.. any ideas?

![Screenshot 2024-08-09 212914](https://github.com/user-attachments/assets/889c1ada-8197-4faa-a2f6-0e546944c96c)

**Comment by RagingCactus** [comment]
Thank you for providing more information. As you can see, providing that even helped yourself to get more insight into the problem.

Your `API_ENDPOINT` and `CLIENT_ENDPOINT` need to exactly match the URL prefix you're using in the browser. Currently, you use (for example) `http://spot.xxx.com/`. This needs to be `https://spot.xxx.com`, as you are using HTTPS. Please also try without the trailing `/`. If that makes a difference this should be fixable, but make sure to test it so we know.

A second thing: I am seeing some weirdness in one of the CORS errors, where the current origin seems to be `http://192.168.1.42:3000`. That should not happen. What is the URL you're using to open the frontend? Is your browser address showing `http://192.168.1.42:3000` at any point? You should be using `https://spot.xxx.com/` to access the frontend in your browser.

**Comment by Techsmith404** [comment]
> Your `API_ENDPOINT` and `CLIENT_ENDPOINT` need to exactly match the URL prefix you're using in the browser. Currently, you use (for example) `http://spot.xxx.com/`. This needs to be `https://spot.xxx.com`, as you are using HTTPS. Please also try without the trailing `/`. If that makes a difference this should be fixable, but make sure to test it so we know.

Yeah I did try with https://spot.xxx.com and https://spot2.xxx.com and it still diddnt work. That's what the log above was from. And I don't have a trailing / in the configs it's being added by the browser

> A second thing: I am seeing some weirdness in one of the CORS errors, where the current origin seems to be `http://192.168.1.42:3000`. That should not happen. What is the URL you're using to open the frontend? Is your browser address showing `http://192.168.1.42:3000` at any point? You should be using `https://spot.xxx.com/` to access the frontend in your browser.

Yeah the cors error was my fault, I forgot to type the address in, instead I just refreshed the page from my local address when that was working. All the errors are the same tho except for the cors error.

I just don't understand why when I have it set to use https, and the website appears as https, it's still saying it's getting mismatched data. I'm at work right now, so I can't do much as far as logs but I'll try to get some posted here in a few if I can

**Comment by Techsmith404** [comment]
Alright so quick update... I just restarted the stack so I could capture some logs, and everything works now. At least, from my phone it does, I won't be in front of a computer untill tonight so I'll make another update then, but assuming everything works ig the solution for cloudflare tunnels is to make sure you put https for all your endpoints instead of http, and use https in the spotify app too. In spotify I have both http and https addresses listed, idk if both are needed but that's how it's setup right now and it's all working so I don't really Wana mess with it too much. Thanks for your help @RagingCactus .  

@CEO-Enzo if you're still having problems try that and see if it helps.

**Comment by Techsmith404** [comment]
Yeah everything works now web and mobile. If you're reading this in the future looking for a solution read the above post. Thank you @RagingCactus for your help
