### ISSUE TITLE
Can't get to run - White screen

### ISSUE THREAD

**Issue by moviemakr1620** [Yooooomi/your_spotify#417]
I've been having the hardest time getting this working. 

As of right now I get the login screen and when i click it and login i get redirected to the wrong address and i get the "INVALID_CLIENT: Invalid redirect URI" message. 
Redirect URL: https://accounts.spotify.com/authorize?client_id=xxxxx&response_type=code&redirect_uri=https%3A%2F%2Fmusicdb.mydomain.com%2Foauth%2Fspotify%2Fcallback&state=nLdJgbIBCVxTr-jU3DSuvwwQqMhyAaJQUnzXdoyr8aU&scope=user-read-private+user-read-email+user-read-recently-played+user-modify-playback-state+playlist-modify-private+playlist-modify-public

When i change the address manually from musicdb to just music it redirects properly but shows only a white screen.

Docker-compose:
version: "3"

services:
  server:
    image: yooooomi/your_spotify_server
    restart: always
    ports:
      - "8580:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      API_ENDPOINT: https://musicdb.mydomain.com
      CLIENT_ENDPOINT: https://music.mydomain.com
      SPOTIFY_PUBLIC: 
      SPOTIFY_SECRET: 

      CORS: i-want-a-security-vulnerability-and-want-to-allow-all-origins
      TIMEZONE: America/New_York
      MONGO_ENDPOINT: mongodb://mongo:27017/your_spotify
      REDIRECT_URI: https://music.mydomain.com/oauth/spotify/callback

  mongo:
    container_name: mongo
    image: mongo:4.4.8
    ports:
     - 27017:27017
    volumes:
      - /volume1/docker/your_spotify_db:/data/db

  web:
    image: yooooomi/your_spotify_client
    restart: always
    ports:
      - "3999:3000"
    environment:
       API_ENDPOINT: https://musicdb.mydomain.com
       REDIRECT_URI: https://music.mydomain.com/oauth/spotify/callback
       
 I use nginx proxy manager.
 forwarded both to the proper ports with websocket enabled.

on the spotify dashboard i have this as the redirect:
https://music.mydomain.com/api/oauth/spotify

the REDIRECT_URI: i put in to force the correct redirect. I have no errors in my logs.

**Comment by RagingCactus** [comment]
> As of right now I get the login screen and when i click it and login i get redirected to the wrong address and i get the "INVALID_CLIENT: Invalid redirect URI" message.
Redirect URL: https://accounts.spotify.com/authorize?client_id=xxxxx&response_type=code&redirect_uri=https%3A%2F%2Fmusicdb.mydomain.com%2Foauth%2Fspotify%2Fcallback&state=nLdJgbIBCVxTr-jU3DSuvwwQqMhyAaJQUnzXdoyr8aU&scope=user-read-private+user-read-email+user-read-recently-played+user-modify-playback-state+playlist-modify-private+playlist-modify-public

This is behaving exactly as it should. The `redirect_uri` parameter sent to Spotify should point to your backend (i.e., your `API_ENDPOINT`), so this is correct.

> on the spotify dashboard i have this as the redirect: 
> https://music.mydomain.com/api/oauth/spotify

This is your issue. You need to configure the application on the Spotify developer site with the following redirect URL for your case: `https://musicdb.mydomain.com/oauth/spotify/callback`

**Comment by moviemakr1620** [comment]
It worked! Thanks so much for taking the time to help me out. I tried so many combinations and was always just shy of making it work.

**Comment by RagingCactus** [comment]
That's great to hear! Please close the issue in this case.
