### ISSUE TITLE
Delete Users

### ISSUE THREAD

**Issue by Flol0** [Yooooomi/your_spotify#42]
Hey how do i delete Users from the Database?

I get Something is wrong with your Spotify Account on one user. Then express-mongo crashes

**Comment by Yooooomi** [comment]
Hello,

It's a bit tricky for the moment to interact with the database, you would have either to remove it completely or do it manually in mongo.

Can you post the logs of the Dockers please?

**Comment by Flol0** [comment]
`mongo    | {"t":{"$date":"2021-07-09T11:35:42.590+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.31.0.4:48196","connectionId":11,"connectionCount":6}}
mongo    | {"t":{"$date":"2021-07-09T11:35:42.591+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn11","msg":"client metadata","attr":{"remote":"172.31.0.4:48196","client":"conn11","doc":{"driver":{"name":"nodejs|Mongoose","version":"3.6.5"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"4.19.0-17-amd64"},"platform":"'Node.js v15.14.0, LE (unified)","version":"3.6.5|5.12.3"}}}
express-mongo | OPTIONS /login 200 0.916 ms - 4
express-mongo | POST /login 200 1015.224 ms - 879
express-mongo | 2021-07-09T11:35:53.388Z [error]: Request failed with status code 403
express-mongo | Error: Request failed with status code 403
express-mongo |     at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
express-mongo |     at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
express-mongo |     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:260:11)
express-mongo |     at IncomingMessage.emit (node:events:381:22)
express-mongo |     at endReadableNT (node:internal/streams/readable:1307:12)
express-mongo |     at processTicksAndRejections (node:internal/process/task_queues:81:21)
express-mongo | node:internal/process/promises:245
express-mongo |           triggerUncaughtException(err, true /* fromPromise */);
express-mongo |           ^
express-mongo |
express-mongo | TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
express-mongo |     at new NodeError (node:internal/errors:329:5)
express-mongo |     at write_ (node:_http_outgoing:745:11)
express-mongo |     at ServerResponse.end (node:_http_outgoing:858:5)
express-mongo |     at /app/src/routes/oauth.js:33:28
express-mongo |     at processTicksAndRejections (node:internal/process/task_queues:94:5) {
express-mongo |   code: 'ERR_INVALID_ARG_TYPE'
express-mongo | }
mongo    | {"t":{"$date":"2021-07-09T11:35:53.481+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn11","msg":"Connection ended","attr":{"remote":"172.31.0.4:48196","connectionId":11,"connectionCount":5}}
mongo    | {"t":{"$date":"2021-07-09T11:35:53.481+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn8","msg":"Connection ended","attr":{"remote":"172.31.0.4:47416","connectionId":8,"connectionCount":3}}
mongo    | {"t":{"$date":"2021-07-09T11:35:53.481+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn6","msg":"Interrupted operation as its client disconnected","attr":{"opId":315}}
mongo    | {"t":{"$date":"2021-07-09T11:35:53.481+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn7","msg":"Connection ended","attr":{"remote":"172.31.0.4:47414","connectionId":7,"connectionCount":2}}
mongo    | {"t":{"$date":"2021-07-09T11:35:53.482+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn6","msg":"Connection ended","attr":{"remote":"172.31.0.4:47412","connectionId":6,"connectionCount":1}}
mongo    | {"t":{"$date":"2021-07-09T11:35:53.481+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn9","msg":"Connection ended","attr":{"remote":"172.31.0.4:47418","connectionId":9,"connectionCount":4}}
express-mongo | [nodemon] app crashed - waiting for file changes before starting...
mongo    | {"t":{"$date":"2021-07-09T11:35:53.482+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn10","msg":"Connection ended","attr":{"remote":"172.31.0.4:47420","connectionId":10,"connectionCount":0}}`

**Comment by Flol0** [comment]
Happens instantly after login with the affected account

**Comment by Yooooomi** [comment]
Thanks I'll have a look today

**Comment by Yooooomi** [comment]
Ok I have been able to reproduce the issue. Your account seemed to be activated but with no Spotify token, I don't know how it happened. The application is not crashing anymore, but you might need to relog to Spotify through the Settings panel.
The new application will be built in a few minutes after the last commit, you can check this [here](https://hub.docker.com/repository/docker/yooooomi/your_spotify_server).

Have a good day and please keep me informed if I can close this issue when you have everything up to date.

**Comment by Yooooomi** [comment]
@Flol0 any news?

**Comment by Flol0** [comment]
Hey sorry,

It doesn't crash anymore but i get the error of something is wrong after clicking relog to Spotify without even being asked to enter Spotify credentials.

**Comment by Yooooomi** [comment]
That's weird, is there any log linked to that error ?

**Comment by Flol0** [comment]
Okay, sorry... It`s working when properly logged into spotify in the browser before

**Comment by Yooooomi** [comment]
Is everything working now?

**Comment by Flol0** [comment]
Yes thank you very much
