### ISSUE TITLE
How to open your_spotify webui on Internet? Need help for configuration.

### ISSUE THREAD

**Issue by SwiftExplorer567** [Yooooomi/your_spotify#421]
Hi, i want to access this app on web as well but i could not configured it.

How can i set this up?

spotify dev panel:
```
Redirect URIs
http://192.168.0.14:8080/oauth/spotify/callback
http://localhost:8080/oauth/spotify/callback
http://localhost:3000/oauth/spotify/callback
http://192.168.0.14:3000/oauth/spotify/callback
```

Cloudflare zerotrust tunnel:

![image](https://github.com/user-attachments/assets/1f6071b3-76fe-4792-8506-62ff1fcad2d2)

Server:
![image](https://github.com/user-attachments/assets/29bf0cf7-fe26-42ee-9234-b7e468576039)

WEB:
![image](https://github.com/user-attachments/assets/a7f03b3c-307c-4502-8a23-7cae3abf4b07)

**Comment by Yooooomi** [comment]
Hello. I think your endpoints should be the ones accessible from the internet and not local ips.

**Comment by SwiftExplorer567** [comment]
yes fixed it
