### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI whenever trying to access the gui for your_spotify (using UNRAID)

### ISSUE THREAD

**Issue by Toastypaws** [Yooooomi/your_spotify#440]
**Describe the bug**

I keep getting "INVALID_CLIENT: Invalid redirect URI" whenever i click the link to the docker repository and I click sign in.
Im using unraid to host it, so ill include some screenshots of my unraid setup.

![Screenshot 2024-10-05 221712](https://github.com/user-attachments/assets/81551877-8bc9-4fc5-ad72-32ca500e3e18)
![Screenshot 2024-10-05 221830](https://github.com/user-attachments/assets/9a7a28a3-04b4-425c-b4dd-c9052f588310)

Ive looked at the other issues and I just have no idea what im doing wrong.

**Comment by switchmaxfx** [comment]
Did you ever solve this? im having the same issue.
