### ISSUE TITLE
Extended streaming history import not working

### ISSUE THREAD

**Issue by Cavonzio** [Yooooomi/your_spotify#452]
**Describe the bug**

Importing Extended streaming history doesnt work. It shows "The initialization failed, maybe your files are wrongly formatted" when importing

**Additional context**

I tried to import the account data a few weeks ago, and that worked fine, now i got the Extended streaming history, but that doesnt work, I tried opening the .json file and its different from the Account Data .json, maybe thats the issue that cause this error when importing?

StreamingHistory_music_0.json (from Account data)

``` 
 {
    "endTime" : "REDACTED",
    "artistName" : "Daft Punk",
    "trackName" : "Motherboard (Drumless Edition)",
    "msPlayed" : 341853
  }
  {
    "endTime" : "REDACTED",
    "artistName" : "Daft Punk",
    "trackName" : "Motherboard (Drumless Edition)",
    "msPlayed" : 72570
  }
```

Streaming_History_Audio_2018-2024_1.json  (from  Extended streaming history)

```
  {
    "ts": "REDACTED",
    "platform": "REDACTED",
    "ms_played": 341853,
    "conn_country": "REDACTED",
    "ip_addr": "REDACTED",
    "master_metadata_track_name": "Motherboard (Drumless Edition)",
    "master_metadata_album_artist_name": "Daft Punk",
    "master_metadata_album_album_name": "Motherboard (Drumless Edition)",
    "spotify_track_uri": "spotify:track:5nuJ5frI7lmdPYjgyoBrqm",
    "episode_name": null,
    "episode_show_name": null,
    "spotify_episode_uri": null,
    "reason_start": "clickrow",
    "reason_end": "trackdone",
    "shuffle": false,
    "skipped": false,
    "offline": false,
    "offline_timestamp": 1699755801,
    "incognito_mode": false
  }
```

**Comment by eurotransient** [comment]
I'm having issues with the extended history import as well.

On selecting the file it says everything looks good, but then it pops an alert at the top of the screen on submit that says the Initialization Failed.

Checking the logs, it runs through the import file and returns an invalid type for each json entry, and at the end returns this error:

```
fy  | [error]  TypeError: Cannot read properties of null (reading 'length')
your_spotify  |     at FullPrivacyImporter.<anonymous> (/app/www/apps/server/lib/tools/importers/full_privacy.js:124:51)
your_spotify  |     at Generator.next (<anonymous>)
your_spotify  |     at fulfilled (/app/www/apps/server/lib/tools/importers/full_privacy.js:5:58)
```

**Comment by Cavonzio** [comment]
> I'm having issues with the extended history import as well.
> 
> On selecting the file it says everything looks good, but then it pops an alert at the top of the screen on submit that says the Initialization Failed.
> 
> Checking the logs, it runs through the import file and returns an invalid type for each json entry, and at the end returns this error:
> 
> ```
> fy  | [error]  TypeError: Cannot read properties of null (reading 'length')
> your_spotify  |     at FullPrivacyImporter.<anonymous> (/app/www/apps/server/lib/tools/importers/full_privacy.js:124:51)
> your_spotify  |     at Generator.next (<anonymous>)
> your_spotify  |     at fulfilled (/app/www/apps/server/lib/tools/importers/full_privacy.js:5:58)
> ```

I have the exact same behavior

**Comment by mroetsc** [comment]
Hello, having the same issue here.
It appears, that Spotify changed their export format.

In the README that comes with the export, it states:

> Here is an example of one song (end_song) streaming data:
>```json
>{
>"ts": "YYY-MM-DD 13:30:30",
>"username": "_________",
>"platform": "_________",
>"ms_played": "_________",
>"conn_country": "_________",
>"ip_addr_decrypted": "___.___.___.___",
>"user_agent_decrypted": "_________",
>"master_metadata_track_name": "_________",
>"master_metadata_album_artist_name:_________",
>"master_metadata_album_album_name:_________",
>"spotify_track_uri:_________",
>"episode_name": "_________",
>"episode_show_name": "_________",
>"spotify_episode_uri:_________",
>"reason_start": "_________",
>"reason_end": "_________",
>"shuffle": "null/true/false",
>"skipped": "null/true/false",
>"offline": "null/true/false",
>"offline_timestamp": "_________",
>"incognito_mode": "null/true/false",
>}
>```

In reality, like @Cavonzio already added, the actual export looks like this:
```json
  {
    "ts": "TS",
    "platform": "PLATFORM",
    "ms_played": 198773,
    "conn_country": "COUNTRY",
    "ip_addr": "IP",
    "master_metadata_track_name": "I Want To Break Free - Remastered 2011",
    "master_metadata_album_artist_name": "Queen",
    "master_metadata_album_album_name": "The Works",
    "spotify_track_uri": "spotify:track:1MsBRSbt5dqJSw3RxXtvCM",
    "episode_name": null,
    "episode_show_name": null,
    "spotify_episode_uri": null,
    "reason_start": "trackdone",
    "reason_end": "trackdone",
    "shuffle": true,
    "skipped": false,
    "offline": false,
    "offline_timestamp": 1713616587,
    "incognito_mode": false
  },
```

So they removed `username` and `user_agent_decrypted` and renamed `ip_addr_decrypted` to `ip_addr`.

This is confirmed by the logs from `docker compose logs`:
```sh
server-1  |  {
server-1  |   "code": "invalid_type",
server-1  |   "expected": "string",
server-1  |   "received": "undefined",
server-1  |   "path": [
server-1  |    966,
server-1  |    "username"
server-1  |   ],
server-1  |   "message": "Required"
server-1  |  },
server-1  |  {
server-1  |   "code": "invalid_type",
server-1  |   "expected": "string",
server-1  |   "received": "undefined",
server-1  |   "path": [
server-1  |    966,
server-1  |    "ip_addr_decrypted"
server-1  |   ],
server-1  |   "message": "Required"
server-1  |  },
server-1  |  {
server-1  |   "code": "invalid_type",
server-1  |   "expected": "string",
server-1  |   "received": "undefined",
server-1  |   "path": [
server-1  |    966,
server-1  |    "user_agent_decrypted"
server-1  |   ],
server-1  |   "message": "Required"
server-1  |  },
```
→ the old names / fields are still expected

I guess this should not be too hard to fix, but I am not really familiar with typescript, unfortunately. 
@Yooooomi please let me know if you need some sample data to test, I have a fresh extended export laying around, waiting to be imported ;)

**Comment by Yooooomi** [comment]
Oh ok github closed this when merging the pull request. A nightly version will shortly be available, I invite you to test it to know if the issue still occurs.

**Comment by Yooooomi** [comment]
The nightly version is available under the `nightly` docker tag. Let me know if you have any issue.

**Comment by Cavonzio** [comment]
> The nightly version is available under the `nightly` docker tag. Let me know if you have any issue.

Updated to the nightly version, and now it's working perfectly. It seems to be even faster than when I imported the Account Data JSON, even though the Extended Streaming History contains five times more data.

**Comment by Yooooomi** [comment]
This is to be expected, the detailed data contains the Spotify uri directly, no need to search the track name through there api. Glad it works well.
