### ISSUE TITLE
importing Data

### ISSUE THREAD

**Issue by oJuuz0u** [Yooooomi/your_spotify#464]
Hi 
I've been trying to add my extended streaming history and every time this prompt show up
 " The initialization failed, maybe your files are wrongly formatted "

Is there a solution ?

**Comment by GenericUsername255** [comment]
Run the nightly build. 

Had the same issue, is now resolved.

**Comment by schumi4** [comment]
Would be great to see a release here for the folks running the lsio image :)

**Comment by oJuuz0u** [comment]
> Run the nightly build.
> 
> Had the same issue, is now resolved.

I Found it but Idk how to run it 

its my first time using docker 
can you tell me how ?

**Comment by faresismail96** [comment]
> > Run the nightly build.
> > Had the same issue, is now resolved.
> 
> I Found it but Idk how to run it
> 
> its my first time using docker can you tell me how ?

Running the nightly build also fixed it for me.
You can add the tag "nightly" to your docker compose file.
example:
`image: yooooomi/your_spotify_server:nightly` (same should go for web)

**Comment by GenericUsername255** [comment]
> > Run the nightly build.
> > Had the same issue, is now resolved.
> 
> I Found it but Idk how to run it
> 
> its my first time using docker can you tell me how ?

You need to be able to run docker compose (Its just a way to tell docker what to do based on a config file).

If you are on windows then i can't help, you probably need docker desktop.

Then you copy the compose file in this repo into a directory and get docker compose to run it.

Everything will be available to anybody on the local network.

Google and chatgpt is your friend, if you have questions feel free to ask.

**Comment by oJuuz0u** [comment]
it worked thanks guys
