### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by samip5** [Yooooomi/your_spotify#51]
Would you be open to supporting kubernetes deployments?

It would probably need an [helm chart ](https://helm.sh/docs/topics/charts/#:~:text=Helm%20uses%20a%20packaging%20format,%2C%20caches%2C%20and%20so%20on.)at least.

**Comment by samip5** [comment]
Yes, I know Kubernetes and I have an cluster to test it on too. That sounds like a good plan.

**Comment by Yooooomi** [comment]
I'm afraid I am not going to work on such an implementation in the near future. I want to focus my motivation on this project on the application itself and it's features.
Thanks for this feedback, I'll close this issue for now
