### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by Dzjee-Doublejou** [Yooooomi/your_spotify#52]
Hi,

As someone who has just started using Linuxbased programming, I have a few questions.

I have a Raspberry Pi 3, with 1 Gig of ram. Is this enough.

As I install docker and import the Github reg, I still can't get your_Spotify to work. I end up with a lot of errors.
The errors are mostly based on things that are not upgraded

Any suggestions?

Would love to hear.

**Comment by Dzjee-Doublejou** [comment]
Sorry, I feel like an absolute noob. But i can't get it fixed. Do you have something like a tutorial :$?

**Comment by Yooooomi** [comment]
Someone wrote a tutorial here tell me if it fits your needs https://www.google.com/amp/s/breadnet.co.uk/installing/amp/

**Comment by Dzjee-Doublejou** [comment]
Thnx again!

The problem I run into now is this:
Now we can start actually using the application. In the same folder as your docker-compose.yml file run docker-compose up and it should whirr away. it took mine around 5 minutes the first time.

I can't find "run docker-compose "

**Comment by Yooooomi** [comment]
Did you install docker-compose? You can do so by following the instructions here https://dev.to/elalemanyo/how-to-install-docker-and-docker-compose-on-raspberry-pi-1mo
I hope you have a 64 bit is installed on your pi otherwise mongo won't start

**Comment by Dzjee-Doublejou** [comment]
Thanks! I am gonna try this. For the 64 bit. As i can't find a 64 bit variant of Rasbian, I'm gonna try it with Ubuntu.

**Comment by Yooooomi** [comment]
I run Ubuntu too on my Pi 4 🙂

**Comment by Yooooomi** [comment]
Hello! Any updates on your issue?

**Comment by Dzjee-Doublejou** [comment]
Hi! I feel so stupid, I just can't get it to work.

I got everything fixed, but keep getting stuck on stuur like this:
Add a Non-Root User to the Docker Group

It looks like I'm not authorised to do stuff.

**Comment by Dzjee-Doublejou** [comment]
Hi! I feel so stupid, but I just can't get it to work.

Keep getting stuck on stuff like this:
Add a Non-Root User to the Docker Group

Also when starting the docker it looks like I'm not authorised to do stuff

**Comment by samip5** [comment]
You need to use `sudo docker-compose` and sudo before any docker commands.

**Comment by thiagogpa** [comment]
> Hi! I feel so stupid, but I just can't get it to work.
> 
> Keep getting stuck on stuff like this: Add a Non-Root User to the Docker Group
> 
> Also when starting the docker it looks like I'm not authorised to do stuff

You need to add your user to the docker group by doing so:
`sudo usermod -aG docker $USER`

After that you can just restart your system and then you should be good to run `docker-compose up -d` on the folder of your docker-compose.yml

**Comment by Yooooomi** [comment]
I'm going to close this issue now since it's not in the scope of the repository. I wish you good luck
