### ISSUE TITLE
Support reverse proxy basedir

### ISSUE THREAD

**Issue by samip5** [Yooooomi/your_spotify#53]
I want to proxy traffic to backend by using `hostname/backend/` path.
If I use two hostnames, I get CORS errors.

![image](https://user-images.githubusercontent.com/1703002/138478618-452f7a49-4433-4d9b-b796-0e411cf710b3.png)

Related to #51

**Comment by Yooooomi** [comment]
This is achievable with nginx.

```
server {
    listen 443;
    server_name spotify.domain.com;

    location / {
        proxy_pass http://localhost:8007/;
    }

    location /api/ {
        proxy_pass http://localhost:8006/;
    }
}
```
