### ISSUE TITLE
Not updating stats?

### ISSUE THREAD

**Issue by Jenni32222** [Yooooomi/your_spotify#54]
It doesn't seem to be updating my stats, I played some songs and they didn't appear in the dashboard. What could I have done wrong?

**Comment by Yooooomi** [comment]
Hello, I'm sorry to hear that you are having trouble using the project.
Could you please share here your docker configuration and the logs? Thanks 😊

**Comment by Jenni32222** [comment]
I used the example docker-compose file from the repo.
Here are my logs
[_your_spotify_logs.txt](https://github.com/Yooooomi/your_spotify/files/7499442/_your_spotify_logs.txt)
:

**Comment by Yooooomi** [comment]
Yeah it seems that Spotify does not give you new songs. Can you try hitting the relog to Spotify button in the settings ?

**Comment by Jenni32222** [comment]
Doesn't seem to do a lot, I installed this yesterday. It does add some songs but it seems to take like a few hours to add them, for example when I listen to a song right now I won't see it within 5 minutes in the dashboard.

**Comment by Yooooomi** [comment]
If it adds some songs then your installation is working.
The issues could come from
- your device listening in private mode
- your device not connected to the internet
- some delay from Spotify about the songs you listened to
I'll have a look at mine tomorrow and I'll tell you if I have delay too, but it could resolve by itself in the next few days :)

**Comment by Yooooomi** [comment]
I just had a look at mine this morning. Since the 4th of November I'm missing quite a few songs too. It only adds few of them per day. It might be Spotify but not sure. I'll investigate this next week.

**Comment by Yooooomi** [comment]
Everything has gone back to normal since the last time, do you still face any issue?

**Comment by Jenni32222** [comment]
Seems to be Spotify then, been working for me for a while again. Thanks!
