### ISSUE TITLE
How can i troubleshoot the API server

### ISSUE THREAD

**Issue by electron2302** [Yooooomi/your_spotify#6]
I am trying to set up the the API docker container behind a reverse proxy and with a subdomain.
Now if I try to access it just by typing its url I get Bad Gateway.
And the frontend says that the CROS header is wrong even if I set it to all.
There are no Logs from the container in docker except some start infos. 

Where and how should I start troubleshooting?

**Comment by Yooooomi** [comment]
Can you upload your `docker-compose.yml` file so I can take a look at it ? Please be sure to hide Spotify credentials.

**Comment by electron2302** [comment]
https://pastebin.com/Nge0NWvL

**Comment by Yooooomi** [comment]
Okay. Is your reverse proxy handling `https://spotify-tracker-api.my.domina` redirecting to the port `8080` of the container? I see that you might be using traefik, what is the current architecture on which you host `your_spotify` ?

**Comment by electron2302** [comment]
Yes I am using traefik v2

> Is your reverse proxy handling https://spotify-tracker-api.my.domina redirecting to the port 8080 of the container?

It should, it works with every other service on the host including the `your_spotify ` frontend, but I don’t see anything in the logs of the api-server. Is that normal? Or can I set a debugging or verbose flag somewhere on the image?

**Comment by Yooooomi** [comment]
The server/api logs every request, so you should be able to see the requests when you try to log in. The thing with CORS has nothing to do with your problem, the CORS are failing because it can't reach your server.
Try to ping your server using `curl` at `/` of the server url you use in the `docker-compose.yml`, it should return `hello`.

**Comment by Yooooomi** [comment]
I found out the issue. The `mongo` service must not be renamed, as I use it as an endpoint in my server code, and my server only starts when it is connected to the database.
Let me know if I can close this issue :)

**Comment by electron2302** [comment]
I guess that this line is causing the problem then.
https://github.com/Yooooomi/your_spotify/blob/f8db665e67498012e82f35a6627010ec54aa6922/server/src/database/index.js#L14
If this is the only point in the code where a name of the DB container (and the name of the DB in the container) is hardcoded, I think it would make sense to outsource that into a environment variable, since it is not to uncommon for multiple projects to run on the same docker host and name conflicts could be avoided easily that way

**Comment by Yooooomi** [comment]
Yes go ahead and make a pull request, taking `mongo` by default, and can be overriden by a `MONGO_ENDPOINT` environment variable ! Would be awesome !

**Comment by Yooooomi** [comment]
Many thanks mate, closing now

**Comment by electron2302** [comment]
I have to thank you for the project 💯
