### ISSUE TITLE
Documentation request: Installation without docker

### ISSUE THREAD

**Issue by sowdust** [Yooooomi/your_spotify#60]
Hi, could you please provide installation instructions without docker? Thanks very much!

**Comment by Yooooomi** [comment]
Hello, no problem, but you want to have a hard time :)
You will need to have
- A mongo database
- NodeJS

## Backend

- Go to the `server` directory and `npm install` in it
- Start the server with the right environment variables, the same as in the docker-compose for `server`:
  - API_ENDPOINT=http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard
  - CLIENT_ENDPOINT=http://localhost:3000
  - SPOTIFY_PUBLIC=__your_spotify_client_id__
  - SPOTIFY_SECRET=__your_spotify_secret__
  - CORS=http://localhost:3000,http://localhost:3001

## Client

- Go to the `client` directory and `npm install` in it
- Run `npm run build`
- In the `build` directory produced, copy `variables.js` into `variables-final.js` and replace the endpoint with the `API_ENDPOINT`, that is the endpoint of your backend
- Host the static website in the `build` directory the way you want, I personally use `serve`

Please tell me if you have any issue while setting this up, I'll update the readme when we successfully host it without docker.

**Comment by samip5** [comment]
> Hello, no problem, but you want to have a hard time :)

No, but it's not always possible to use Docker, in the case of shared webapp hosting servers for example. ;)

**Comment by Yooooomi** [comment]
Hello, did you succeed in setting it without docker ?

**Comment by samip5** [comment]
If you're asking me, I have a little dilemma with MongoDB as I need to deploy that too so that I can deploy your_spotify. :)

**Comment by Yooooomi** [comment]
You don't want to host this kind of database only for this project ?

**Comment by sowdust** [comment]
Hi all, sorry, I was away for the holidays. I almost succeded setting this up, but at the end as a result I was getting error code 404 instead of the homepage. I think it could be related to some incorrect config settings.
However, it seemed to me that the project is dependent on various vulnerable npm packages - which made me temporarily stop its deployment.

**Comment by Yooooomi** [comment]
I should update all those packages you're right, I might do it soon. If you're interested in upgrading them feel free to open a pull request :)

**Comment by samip5** [comment]
> I should update all those packages you're right, I might do it soon. If you're interested in upgrading them feel free to open a pull request :)

Please take a look at my PR #61. I wasn't quite able to figure everything out but should mostly work.

**Comment by samip5** [comment]
I was able to deploy the instance with the help of .env file and systemd user units. :)

**Comment by Yooooomi** [comment]
Installation with docker is pushed to master, tell me if there is anything missing so we can close this

**Comment by samip5** [comment]
> Installation with docker is pushed to master, tell me if there is anything missing so we can close this

There's not I my opinion but using systemd user unit files to set it up might be worthy to do docs for too as that's how I'm running it at least.

**Comment by Yooooomi** [comment]
Yes it might be interesting to document it in LOCAL_INSTALL.md. However I have no knowledge in this domain so it would be very cool if you could write something quick about it :)

**Comment by Yooooomi** [comment]
If you feel like what we merged about system user unit is fine, feel free to close this issue :)
