### ISSUE TITLE
Frontend URL routing

### ISSUE THREAD

**Issue by samip5** [Yooooomi/your_spotify#62]
Why is it that some of urls go to things like /login, and /register but if I refresh the page with that in the URL, it yells 404?

Using apache to directly serve the build directory, and it does work though.

**Comment by samip5** [comment]
This needs to be documented: https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing

**Comment by Yooooomi** [comment]
You need to redirect every 404 to index.html and it will work. I will document it as soon as I add the hosting without docker to the readme

**Comment by Yooooomi** [comment]
I documented it in the local installation guide
