### ISSUE TITLE
Lost my password

### ISSUE THREAD

**Issue by BHAALOL** [Yooooomi/your_spotify#64]
Hi,
I lost my password account...
I can't find how to reset it, I tried to open the database but it didn't work...
Do you have a tutorial or documentation to help me?

Thanks in advance !  
& Happy New Year

**Comment by Yooooomi** [comment]
Hello, sorry for not getting back to you. I have been under a lot of work lately. I'll try to implement a script that allows you to change or reset your password.

**Comment by Yooooomi** [comment]
In the last update you can access the platform with another account and change the password of any account you want

**Comment by BHAALOL** [comment]
Nice thanks i ll try !

**Comment by Yooooomi** [comment]
I'll close this since now you can one's password from the settings

**Comment by BHAALOL** [comment]
Hello, I'm sorry I couldn't answer earlier, thanks for this new feature!
I'll try it as soon as possible!

Le jeu. 3 févr. 2022 à 22:52, Timothee Boussus ***@***.***> a
écrit :
