### ISSUE TITLE
Is the colorful history graph comming back?

### ISSUE THREAD

**Issue by Kl4rry** [Yooooomi/your_spotify#78]
I just updated and noticed that the colorful history graph is gone. Is it comming back or will i have to revert to an older version to have it back?

**Comment by Yooooomi** [comment]
Hello! I did not know if anyone loved this graph or not, of course if you liked it I can implement it back.

**Comment by Kl4rry** [comment]
It was my favorite graph.

**Comment by Yooooomi** [comment]
I will implement it by the beginning of next week don't worry, sorry for this

**Comment by Yooooomi** [comment]
The colorful graph you're talking about is about to be released on dockerhub. Tell me if there is anything missing. If not feel free to close this issue :)

**Comment by Kl4rry** [comment]
Cool!
