### ISSUE TITLE
Is the artist genre information coming back?

### ISSUE THREAD

**Issue by samip5** [Yooooomi/your_spotify#79]
I loved the details about Artists, where did it go?

I think it should be on the top artists page visiable and/or in the artists own page aswell as ability to browse just the Artist genres like genz artists that one has listened to.

**Comment by Yooooomi** [comment]
Hello again 👋
Genres in Spotify API are a mess. They're only useful to be displayed but I can't make stats about them. They are plain strings that are never the same. You can find genres like "a bit like hip-hop" (maybe not but it's close to this). I can add the genres to the artist page and the artist list on the top artists page however.

**Comment by samip5** [comment]
Yeah, I only want them to be displayed. :)

**Comment by Yooooomi** [comment]
The artist genres are being released to dockerhub, tell me if you expect something more or we can close this issue.

**Comment by samip5** [comment]
> The artist genres are being released to dockerhub, tell me if you expect something more or we can close this issue.

I updated my local_install today, and I'm not seeing Artist genres?

**Comment by Yooooomi** [comment]
It's weird cause they're here https://github.com/Yooooomi/your_spotify/blob/master/client/src/scenes/ArtistStats/ArtistStats.tsx#L52
