### ISSUE TITLE
FR: More interval choices, preferably with a date picker

### ISSUE THREAD

**Issue by samip5** [Yooooomi/your_spotify#82]
It would be nice to able to choose the interval to search data about when there's multiple years worth of data.

Like if I want to search only for data inside 2019 or 2020. I should be able to choose that.

**Comment by samip5** [comment]
I also don't think that the interval's should always end to today, if I want last day, I want JUST last day. :)

**Comment by Yooooomi** [comment]
I had that in the last version, a date picker could be good yes. I'll work on this

**Comment by Yooooomi** [comment]
The date picker is being released on dockerhub, tell me if you think there could be more. If you don't think so, feel free to close this issue :)

**Comment by joshuayuen99** [comment]
Not the original author but it looks great! Would it be possible to only show the songs played within the selected time frame in your song history? Though I think the default behavior should be as it currently is (infinitely scrolling). Maybe have a checkbox or something to only display songs from the selected time frame?

**Comment by Yooooomi** [comment]
@joshuayuen99 this is a good idea to have the history related to the time frame selected. I'll work on it this week if I have time.

**Comment by samip5** [comment]
> Not the original author but it looks great! Would it be possible to only show the songs played within the selected time frame in your song history? Though I think the default behavior should be as it currently is (infinitely scrolling). Maybe have a checkbox or something to only display songs from the selected time frame?

This is what I originally meant by by the FR. @Yooooomi  :)

**Comment by Yooooomi** [comment]
Currently you can for everything but the history, might implement the history in the evening.

**Comment by samip5** [comment]
> Currently you can for everything but the history, might implement the history in the evening.

Isin't the history the most useful thing to look at during specific timespan? :)

**Comment by Yooooomi** [comment]
Maybe, if you think so. The thing is the timespan was easy and quick to implement on graph since they already rely on timespans. It's not the same for history and would require a bit more work, that's why I did not do this a sunday evening yesterday ^^

**Comment by Yooooomi** [comment]
Interval in history is now a thing :)
