### ISSUE TITLE
 FR: More detailed history date information

### ISSUE THREAD

**Issue by joshuayuen99** [Yooooomi/your_spotify#84]
I think it would be a nice addition to also show the date you listened to a track on in your history (eg. "2/19 13:04" instead of just "13:04"), especially when looking at a longer period of time than just the last 24h.

Alternatively, maybe instead of the column being "listened at", having it in terms of how long ago you listened to it (eg. "5 mins ago", "2 hours ago", "3 days ago", "10 weeks ago"), and having it show the full date/time if you hovered over it would be more insightful. :-)

**Comment by Yooooomi** [comment]
The normal behavior of this is only the hours and minutes if it's the same day, and it starts giving dates when it's older than 24 hours

**Comment by joshuayuen99** [comment]
I see! I hadn't gotten a chance to see the existing functionality as I only had access to the previous 24 hours worth of data. On second thought, I agree that past 24 hours, having a "day ago" or longer would mostly hurt in that regard. Though I think maybe there's still value in having values < 24 hours shown in the "x minutes/hours ago" format, and showing the exact time on hover? I could be in the minority there.

Either way, this is a great tool, thanks for making it! I'm looking forward to getting more of my data from Spotify as I'm quite curious what my overall data looks like :-)

**Comment by Yooooomi** [comment]
I don't know what I think about this, I think it all depends on the point of view. Maybe adding a preference about this in the settings would satisfy both of us but is it overkill? I might want to close this since this is a personal only changement. I don't know what you think about this one. I'm open to discussing it further by taking real life examples.

**Comment by Yooooomi** [comment]
I'm going to close this since we have no clear answer to this.
