### ISSUE TITLE
Feature Request: Stop new Registrations

### ISSUE THREAD

**Issue by electron2302** [Yooooomi/your_spotify#9]
I would appreciate it if I cloud Lock down the registration, either thru the dashboard or over an Environment variable

**Comment by Yooooomi** [comment]
Yes I thought about that as you don't want people to use your service without your permission. 
Will keep in touch here about this

**Comment by electron2302** [comment]
In my opinion there are two different approaches.

First: The API server has a state in which he just blocks new registrations. This could be controlled over an environment variable or it could be an option that can be changed in the dashboard. If you would want this option in the dashboard it is more accessible the in a docker-compose file, but would be accessible to all users, since there are no user roles (at least from what I have seen)

Second: You could ask for a fix password, let’s call it account-creation-token, only people who know it can create an account. Pro: no changing states / behavior. Con: Frontend Change required

**Comment by vimodev** [comment]
I remedied this for now by using auth_basic in my nginx reverse proxy.

**Comment by Yooooomi** [comment]
Closing since last update added this feature, thanks for the idea
