### ISSUE TITLE
[Feature Request] Remove "Register Instead" hyperlink when new registers are disabled

### ISSUE THREAD

**Issue by AzamServer** [Yooooomi/your_spotify#90]
Type: Feature Request
Issue Name: Remove "Register Instead" hyperlink when new registers are disabled
Description: A nice web GUI enhancement would be when new registers are disabled, the "Register Instead" hyperlink underneath the "Login" button would be removed. However, the "Register Instead" hyperlink would be present when new registers are enabled obviously.

**Comment by Yooooomi** [comment]
Hello!
Thanks for your feedback, this is great idea that I think I'll implement.

**Comment by Yooooomi** [comment]
Hello, since last release, I don't think this is still up to date, there is now only one button for logging in and registering.
