### ISSUE TITLE
Support extended playing history export

### ISSUE THREAD

**Issue by samip5** [Yooooomi/your_spotify#96]
The format is different, it's as follows:

```json
{
"ts": "YYY-MM-DD 13:30:30",
"username": "_________",
"platform": "_________",
"ms_played": _________,
"conn_country": "_________",
"ip_addr_decrypted": "___.___.___.___", 
"user_agent_decrypted": "_________", 
"master_metadata_track_name": "_________", 
“master_metadata_album_artist_name:_________”, 
“master_metadata_album_album_name:_________", 
“spotify_track_uri:_________”,
"episode_name": _________", 
"episode_show_name": _________", 
“spotify_episode_uri:_________”,
"reason_start": "_________",
"reason_end": "_________",
"shuffle": null/true/false,
"skipped": null/true/false,
"offline": null/true/false,
"offline_timestamp": _________,
"incognito_mode": null/true/false,
}
```

**Comment by samip5** [comment]
My one file has like 16k entries... :D

**Comment by samip5** [comment]
<img width="1055" alt="Screenshot 2022-03-04 at 14 49 10" src="https://user-images.githubusercontent.com/1703002/156766428-236ea691-55a2-412c-9687-0ab97bef1050.png">

**Comment by flighter18** [comment]
oh yea!
that would be great, if that would work :)

i had the same problem. Couldn't import the extended playing history.

**Comment by Yooooomi** [comment]
I just received mine today, I'll work on this this weekend. I might have already worked on stabilizing the import system and enhanced it 👀

**Comment by Yooooomi** [comment]
Check out last release :)

**Comment by flighter18** [comment]
@Yooooomi 
thank u. :)

but I'm getting an error massage, when i import the endsong data.
Should i open a new issue?

```
spotify_express-mongo |       code: 'invalid_type',
spotify_express-mongo |       expected: 'boolean',
spotify_express-mongo |       received: 'null',
spotify_express-mongo |       path: [Array],
spotify_express-mongo |       **message: 'Expected boolean, received null'**
spotify_express-mongo |     },

```
```
spotify_express-mongo | [error]  **TypeError: Cannot read properties of null (reading 'length'**)
spotify_express-mongo |     at FullPrivacyImporter.<anonymous> (/app/lib/tools/importers/full_privacy.js:98:51)
spotify_express-mongo |     at Generator.next (<anonymous>)
spotify_express-mongo |     at fulfilled (/app/lib/tools/importers/full_privacy.js:5:58)
spotify_express-mongo | POST /import/full-privacy 400 734.900 ms - 29
```

**Comment by flighter18** [comment]
I created a new issue :) 
doesn't mind my comment here.

**Comment by samip5** [comment]
> Check out last release :)

![image](https://user-images.githubusercontent.com/1703002/157324664-2b4c3a08-3826-4dd3-89fd-f706af98b818.png)

;)

**Comment by Yooooomi** [comment]
@samip5 WOW, tell me if it runs smoothly. If you're running a Pi, don't even try to request all the stats xD

**Comment by samip5** [comment]
> @samip5 WOW, tell me if it runs smoothly. If you're running a Pi, don't even try to request all the stats xD

Yeah, not running on a Pi but rather on an Dell R6515, with AMD EPYC 7402P. The compiled it very fast. :)
