### ISSUE TITLE
Error importing extended playing history

### ISSUE THREAD

**Issue by flighter18** [Yooooomi/your_spotify#98]
**Describe the bug**
When i push the button to start the endsong file import. i get following error:

```
spotify_express-mongo |       code: 'invalid_type',
spotify_express-mongo |       expected: 'boolean',
spotify_express-mongo |       received: 'null',
spotify_express-mongo |       path: [Array],
spotify_express-mongo |       **message: 'Expected boolean, received null'**
spotify_express-mongo |     },
```

```
spotify_express-mongo | [error]  **TypeError: Cannot read properties of null (reading 'length'**)
spotify_express-mongo |     at FullPrivacyImporter.<anonymous> (/app/lib/tools/importers/full_privacy.js:98:51)
spotify_express-mongo |     at Generator.next (<anonymous>)
spotify_express-mongo |     at fulfilled (/app/lib/tools/importers/full_privacy.js:5:58)
spotify_express-mongo | POST /import/full-privacy 400 734.900 ms - 29
```

So the import dosen't starts.

**Expected behavior**
Import of the data will start without any errors.

**Comment by Yooooomi** [comment]
Oh that's interesting, can you send me your endsong files on my discord Marvin the Martian#8336, so that it stays private. You may have a null value where I had only boolean values.

**Comment by flighter18** [comment]
couldn't find you on discord (actually i am a noop on discourd that could be the reason :) )
i could find you on facebook if you don't mind i will send you the files on facebook?

**Comment by Yooooomi** [comment]
Give me your @flighter18 I'll add you :)

**Comment by flighter18** [comment]
ok :) 
flighter#1203

**Comment by Yooooomi** [comment]
I added you

**Comment by Yooooomi** [comment]
Okay I fixed the problem. The problem was in the file validation process for the full privacy import.
Will be fixed when this action ends https://github.com/Yooooomi/your_spotify/actions/runs/1941199092

**Comment by flighter18** [comment]
it worked like a charm :)
Thank u
